apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: smarterp

resources:
  - ../../../base/coreapp
  - ../../../base/shared

images:
  - name: smarterp/smarterp-coreapp
    newName: etsoo-registry.cn-qingdao.cr.aliyuncs.com/smarterp/smarterp-coreapp

secretGenerator:
  # 生成应用配置环境变量
  - name: coreapp-secrets
    envs:
      - coreapp.env.secrets

patches:
  # 仅 CN 注入 imagePullSecrets
  - target:
      kind: Deployment
      name: smarterp-coreapp
    patch: |-
      - op: add
        path: /spec/template/spec/imagePullSecrets
        value:
          - name: aliyun-acr-secret
