# Docker Compose file for SmartERP
# SmartERP 的 Docker Compose 文件

services:
  # Postgres database for SmartERP
  # name: 'etsoo', db: 'smarterp', user: 'smarterp'
  # for 17, volumes, ./data/postgres:/var/lib/postgresql/data
  # 司友云ERP(SmartERP)的 Postgres 数据库
  postgres:
    image: postgres:18.4-alpine
    container_name: postgres.app.local
    restart: unless-stopped
    environment:
      POSTGRES_USER: smarterp
      POSTGRES_PASSWORD: smarterp
      POSTGRES_DB: smarterp
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql
    networks:
      - etsoo

  # PgAdmin4 for Postgres management
  # 用于 Postgres 管理的 PgAdmin4
  pgadmin:
    depends_on:
      - postgres
    image: dpage/pgadmin4:latest
    container_name: pgadmin.app.local
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@etsoo.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_LISTEN_PORT: 5501
    ports:
      - "5501:5501"
    volumes:
      - ./data/pgadmin:/var/lib/pgadmin
    networks:
      - etsoo

  # RabbitMQ for message queue
  # 消息队列的 RabbitMQ
  rabbitmq:
    image: rabbitmq:4.3.1-management-alpine
    container_name: rabbitmq.app.local
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./data/rabbitmq:/var/lib/rabbitmq
    networks:
      - etsoo

  # Etsoo Local setup
  # 亿速思维本地设置
  localsetup:
    image: localsetup
    # tty: true # For infinite running
    # stdin_open: true
    build:
      context: .
      dockerfile: Resources/LocalSetupDocker
    container_name: localsetup
    volumes:
      - certs:/var/etsoo/certs
      - ./data/certs:/var/etsoo/hostcerts
    networks:
      - etsoo

  # Distributed Cache (like Redis)
  garnet:
    image: "ghcr.io/microsoft/garnet"
    container_name: garnet.app.local
    restart: unless-stopped
    ulimits:
      memlock: -1
    ports:
      - "6379:6379"
    # network_mode: "host"
    volumes:
      - garnetdata:/data
    networks:
      - etsoo

  # Redis Insight for Redis management
  # http://garnetui.app.local/, host: garnet.app.local, no username and password
  redis-insight:
    depends_on:
      - garnet
    image: redis/redisinsight:latest
    container_name: garnetui.app.local
    restart: unless-stopped
    ports:
      - "5540:5540"
    networks:
      - etsoo

  # minio, API compatible with Amazon S3 cloud storage service
  # Create the folder instead of using the "MINIO_DEFAULT_BUCKETS" in standalone mode
  minio:
    image: minio/minio:latest
    container_name: minio.app.local
    restart: unless-stopped
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=password
      - MINIO_PROMETHEUS_AUTH_TYPE=public
      - MINIO_UPDATE=off
    entrypoint:
      - sh
      - -euc
      - |
        mkdir -p /data/smarterp && \
        minio server --address "0.0.0.0:8900" --console-address "0.0.0.0:8901" /data
    ports:
      - "8900:8900"
      - "8901:8901"
    volumes:
      - ./data/minio:/data
    networks:
      - etsoo

  # seq, port 80 for web, 5341 for API, 45341 for ingestion
  seq:
    image: datalust/seq:latest
    container_name: seq.app.local
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "5330:80"
      - "5331:5341"
      - "45341:45341"
    volumes:
      - ./data/seq:/data
    networks:
      - etsoo

  # Platform site
  # Use default dev certificate inside docker:
  # dotnet dev-certs https -ep "%USERPROFILE%\.aspnet\https\aspnetapp.pfx" -p etsoo --trust
  # volumes: - $USERPROFILE/.aspnet/https:/root/.aspnet/https:ro
  # - Kestrel__Certificates__Default__Path=/root/.aspnet/https/aspnetapp.pfx
  # - Kestrel__Certificates__Default__Password=etsoo
  etsoo-platform:
    depends_on:
      - postgres
      - rabbitmq
    image: ${DOCKER_REGISTRY-}etsoo-platform
    build:
      context: .
      dockerfile: Platform/Platform.Server/Dockerfile
    container_name: platform.app.local
    environment:
      - DOTNET_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080;80
      - ASPNETCORE_HTTPS_PORTS=8081;443
      - ETSOO_ENVIRONMENT=Docker
    ports:
      - "9702:8081"
    volumes:
      - $APPDATA/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - certs:/etc/etsoo/certs
    networks:
      - etsoo

  # Worker Center for background tasks
  etsoo-workercenter:
    depends_on:
      - etsoo-platform
    image: ${DOCKER_REGISTRY-}etsoo-workercenter
    container_name: etsoo-workercenter
    build:
      context: .
      dockerfile: WorkerCenter/Dockerfile
    environment:
      - DOTNET_ENVIRONMENT=Development
    volumes:
      - $APPDATA/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
    networks:
      - etsoo

  # CMS worker Center for background tasks
  etsoo-workercms:
    depends_on:
      - etsoo-platform
    image: ${DOCKER_REGISTRY-}etsoo-workercms
    container_name: etsoo-workercms
    build:
      context: .
      dockerfile: WorkerCMS/Dockerfile
    environment:
      - DOTNET_ENVIRONMENT=Development
    volumes:
      - $APPDATA/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
    networks:
      - etsoo

  # CoreApp site
  etsoo-coreapp:
    image: ${DOCKER_REGISTRY-}etsoo-coreapp
    depends_on:
      - etsoo-platform
    build:
      context: .
      dockerfile: CoreApp/CoreApp.Server/Dockerfile
    container_name: core.app.local
    environment:
      - DOTNET_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080;80
      - ASPNETCORE_HTTPS_PORTS=8081;443
      - ETSOO_ENVIRONMENT=Docker
    ports:
      - "9705:8081"
    volumes:
      - $APPDATA/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - certs:/etc/etsoo/certs
    networks:
      - etsoo

  # Admin site
  etsoo-admin:
    image: ${DOCKER_REGISTRY-}etsoo-admin
    depends_on:
      - etsoo-platform
    build:
      context: .
      dockerfile: Admin/Admin.Server/Dockerfile
    container_name: admin.app.local
    environment:
      - DOTNET_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080;80
      - ASPNETCORE_HTTPS_PORTS=8081;443
      - ETSOO_ENVIRONMENT=Docker
    ports:
      - "9708:8081"
    volumes:
      - $APPDATA/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - certs:/etc/etsoo/certs
    networks:
      - etsoo

  # CRM site
  etsoo-crm:
    image: ${DOCKER_REGISTRY-}etsoo-crm
    depends_on:
      - etsoo-platform
    build:
      context: .
      dockerfile: CRM/CRM.Server/Dockerfile
    container_name: crm.app.local
    environment:
      - DOTNET_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080;80
      - ASPNETCORE_HTTPS_PORTS=8081;443
      - ETSOO_ENVIRONMENT=Docker
    ports:
      - "9711:8081"
    volumes:
      - $APPDATA/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - certs:/etc/etsoo/certs
    networks:
      - etsoo

  # Nginx for reverse proxy
  # Change the nginx.conf under root for your needs, make sure the ports (80, 443) are not used by other services (like IIS)
  # Nginx 用于反向代理
  # 修改根目录下的 nginx.conf 文件以适应你的需求，确保(80, 443)端口没有被其他服务占用（如 IIS）
  nginx:
    image: nginx:1.31.2-alpine
    container_name: nginx
    depends_on:
      - etsoo-coreapp
      - etsoo-admin
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Resources/nginx.conf:/etc/nginx/nginx.conf
      - ./data/nginx/logs:/etc/nginx/logs
      - ./data/nginx/cache:/var/cache/nginx
      - certs:/etc/nginx/ssl
    networks:
      - etsoo

volumes:
  certs:
    name: "dev-certs"
  garnetdata:
    name: "garnet-data"

networks:
  etsoo:
