events {
}

http {
	# All certificates are created within LocalSetupDocker
	server {
		listen              80;
		listen              443 ssl;
		server_name         pgadmin.app.local;
		ssl_certificate     ssl/cert.pem;
		ssl_certificate_key ssl/key.pem;

		location / {
			# Define the proxy pass to the pgAdmin container, the port is the internal port of the container
			proxy_set_header   X-Forwarded-For $remote_addr;
			proxy_set_header   Host $host;
			proxy_pass         http://pgadmin:80;
			proxy_buffering    on;
		}
	}
}