apiVersion: v1
kind: Secret
metadata:
  name: shared-secrets
type: Opaque
stringData:
  {{- .Values.secrets.shared | regexReplaceAll "(?m)^\\s*#.*$\\n?" "" | regexReplaceAll "(?m)^\\s*$\\n?" "" | replace "'" "''" | regexReplaceAll "(?m)^([^=\\n]+)=(.*)$" "${1}: '${2}'" | nindent 2 }}

---
apiVersion: v1
kind: Secret
metadata:
  name: admin-secrets
type: Opaque
stringData:
  {{- .Values.secrets.admin | regexReplaceAll "(?m)^\\s*#.*$\\n?" "" | regexReplaceAll "(?m)^\\s*$\\n?" "" | replace "'" "''" | regexReplaceAll "(?m)^([^=\\n]+)=(.*)$" "${1}: '${2}'" | nindent 2 }}

---
apiVersion: v1
kind: Secret
metadata:
  name: coreapp-secrets
type: Opaque
stringData:
  {{- .Values.secrets.coreapp | regexReplaceAll "(?m)^\\s*#.*$\\n?" "" | regexReplaceAll "(?m)^\\s*$\\n?" "" | replace "'" "''" | regexReplaceAll "(?m)^([^=\\n]+)=(.*)$" "${1}: '${2}'" | nindent 2 }}

---
apiVersion: v1
kind: Secret
metadata:
  name: crm-secrets
type: Opaque
stringData:
  {{- .Values.secrets.crm | regexReplaceAll "(?m)^\\s*#.*$\\n?" "" | regexReplaceAll "(?m)^\\s*$\\n?" "" | replace "'" "''" | regexReplaceAll "(?m)^([^=\\n]+)=(.*)$" "${1}: '${2}'" | nindent 2 }}

---
apiVersion: v1
kind: Secret
metadata:
  name: platform-secrets
type: Opaque
stringData:
  {{- .Values.secrets.platform | regexReplaceAll "(?m)^\\s*#.*$\\n?" "" | regexReplaceAll "(?m)^\\s*$\\n?" "" | replace "'" "''" | regexReplaceAll "(?m)^([^=\\n]+)=(.*)$" "${1}: '${2}'" | nindent 2 }}

---
apiVersion: v1
kind: Secret
metadata:
  name: workercenter-secrets
type: Opaque
stringData:
  {{- .Values.secrets.workercenter | regexReplaceAll "(?m)^\\s*#.*$\\n?" "" | regexReplaceAll "(?m)^\\s*$\\n?" "" | replace "'" "''" | regexReplaceAll "(?m)^([^=\\n]+)=(.*)$" "${1}: '${2}'" | nindent 2 }}

---
apiVersion: v1
kind: Secret
metadata:
  name: workercms-secrets
type: Opaque
stringData:
  {{- .Values.secrets.workercms | regexReplaceAll "(?m)^\\s*#.*$\\n?" "" | regexReplaceAll "(?m)^\\s*$\\n?" "" | replace "'" "''" | regexReplaceAll "(?m)^([^=\\n]+)=(.*)$" "${1}: '${2}'" | nindent 2 }}
