apiVersion: v1
kind: Secret
metadata:
  name: shared-secrets
type: Opaque
stringData: {{ - .Files.Get "config/secrets/shared.env.secrets" | nindent 2 }}

---
apiVersion: v1
kind: Secret
metadata:
  name: admin-secrets
type: Opaque
stringData: {{ - .Files.Get "config/secrets/admin.env.secrets" | nindent 2 }}

---
apiVersion: v1
kind: Secret
metadata:
  name: coreapp-secrets
type: Opaque
stringData:
  {{ - .Files.Get "config/secrets/coreapp.env.secrets" | nindent 2 }}

---
apiVersion: v1
kind: Secret
metadata:
  name: crm-secrets
type: Opaque
stringData: {{ - .Files.Get "config/secrets/crm.env.secrets" | nindent 2 }}

---
apiVersion: v1
kind: Secret
metadata:
  name: platform-secrets
type: Opaque
stringData:
  {{ - .Files.Get "config/secrets/platform.env.secrets" | nindent 2 }}

---
apiVersion: v1
kind: Secret
metadata:
  name: workercenter-secrets
type: Opaque
stringData:
  {{ - .Files.Get "config/secrets/workercenter.env.secrets" | nindent 2 }}

---
apiVersion: v1
kind: Secret
metadata:
  name: workercms-secrets
type: Opaque
stringData:
  {{ - .Files.Get "config/secrets/workercms.env.secrets" | nindent 2 }}
