apiVersion: v1
kind: Secret
metadata:
  name: shared-secrets
type: Opaque
stringData:
  {{- include "chart.envToYaml" .Values.secrets.shared | nindent 2 }}

---
apiVersion: v1
kind: Secret
metadata:
  name: admin-secrets
type: Opaque
stringData:
  {{- include "chart.envToYaml" .Values.secrets.admin | nindent 2 }}

---
apiVersion: v1
kind: Secret
metadata:
  name: coreapp-secrets
type: Opaque
stringData:
  {{- include "chart.envToYaml" .Values.secrets.coreapp | nindent 2 }}

---
apiVersion: v1
kind: Secret
metadata:
  name: crm-secrets
type: Opaque
stringData:
  {{- include "chart.envToYaml" .Values.secrets.crm | nindent 2 }}

---
apiVersion: v1
kind: Secret
metadata:
  name: platform-secrets
type: Opaque
stringData:
  {{- include "chart.envToYaml" .Values.secrets.platform | nindent 2 }}

---
apiVersion: v1
kind: Secret
metadata:
  name: workercenter-secrets
type: Opaque
stringData:
  {{- include "chart.envToYaml" .Values.secrets.workercenter | nindent 2 }}

---
apiVersion: v1
kind: Secret
metadata:
  name: workercms-secrets
type: Opaque
stringData:
  {{- include "chart.envToYaml" .Values.secrets.workercms | nindent 2 }}
