<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>429ac826-bf69-4687-bdde-580892d2f185</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    <DockerfileContext>..\..</DockerfileContext>
    <SpaRoot>..\coreapp.client</SpaRoot>
    <SpaProxyLaunchCommand>npm run dev</SpaProxyLaunchCommand>
    <SpaProxyServerUrl>https://localhost:9005</SpaProxyServerUrl>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="com.etsoo.DI" Version="1.0.17" />
    <PackageReference Include="com.etsoo.GarnetClient" Version="1.0.2" />
    <PackageReference Include="com.etsoo.ServiceApp" Version="1.2.73" />
    <PackageReference Include="com.etsoo.ThirdPartyExtentions" Version="1.0.3" />
    <PackageReference Include="EfCore.SchemaCompare" Version="8.2.0" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="8.0.12" />
    <PackageReference Include="Microsoft.AspNetCore.SpaProxy">
      <Version>8.0.12</Version>
    </PackageReference>
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.21.0" />
    <PackageReference Include="OpenTelemetry.Exporter.Console" Version="1.11.0" />
    <PackageReference Include="OpenTelemetry.Extensions.Hosting" Version="1.11.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="7.2.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\PlatformShared\PlatformShared.csproj" />
    <ProjectReference Include="..\coreapp.client\coreapp.client.esproj">
      <ReferenceOutputAssembly>false</ReferenceOutputAssembly>
    </ProjectReference>
  </ItemGroup>

</Project>
