apiVersion: apps/v1
kind: Deployment
metadata:
  name: smarterp-crm
  namespace: smarterp
  labels:
    app: smarterp-crm
spec:
  replicas: {{ .Values.replicaCount | default 1 }}
  selector:
    matchLabels:
      app: smarterp-crm
  template:
    metadata:
      labels:
        app: smarterp-crm
    spec:
      {{- if .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml .Values.global.imagePullSecrets | nindent 8 }}
      {{- end }}
      containers:
        - name: smarterp-crm
          image: "{{ .Values.global.imageRegistry }}/smarterp-crm:{{ .Values.imageTag | default .Values.global.imageTag }}"
          ports:
            - containerPort: 8080
              name: http
          env:
            - name: DOTNET_ENVIRONMENT
              value: "Production"
            - name: ASPNETCORE_HTTP_PORTS
              value: "8080"
          envFrom:
            - secretRef:
                name: shared-secrets
            - secretRef:
                name: crm-secrets
