<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>82c1b486-7653-4980-93a1-7000968472fc</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    <DockerfileContext>..\..</DockerfileContext>
    <DockerComposeProjectPath>..\..\..\docker-compose.dcproj</DockerComposeProjectPath>
    <SpaRoot>..\platform.client</SpaRoot>
    <SpaProxyLaunchCommand>npm run dev</SpaProxyLaunchCommand>
    <SpaProxyServerUrl>https://localhost:9002</SpaProxyServerUrl>
    <PublishAot>false</PublishAot>
    <JsonSerializerIsReflectionEnabledByDefault>false</JsonSerializerIsReflectionEnabledByDefault>
    <SatelliteResourceLanguages>en;zh-Hans;zh-Hant</SatelliteResourceLanguages>
	<EnableConfigurationBindingGenerator>true</EnableConfigurationBindingGenerator>
  </PropertyGroup>

  <ItemGroup>
    <None Include="efpt.config.json.user" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AspNetCore.HealthChecks.NpgSql" Version="9.0.0" />
    <PackageReference Include="com.etsoo.AliAmapApi" Version="1.0.1" />
    <PackageReference Include="com.etsoo.AlipayApi" Version="1.0.10" />
    <PackageReference Include="com.etsoo.ApiProxy" Version="1.0.62" />
    <PackageReference Include="com.etsoo.BaiduApi" Version="1.0.25" />
    <PackageReference Include="com.etsoo.GarnetClient" Version="1.0.2" />
    <PackageReference Include="com.etsoo.GoogleApi" Version="1.0.42" />
    <PackageReference Include="com.etsoo.HtmlIO" Version="1.0.82" />
    <PackageReference Include="com.etsoo.ImageUtils" Version="1.1.0" />
    <PackageReference Include="com.etsoo.Localization" Version="1.0.47" />
    <PackageReference Include="com.etsoo.MicrosoftApi" Version="1.0.11" />
    <PackageReference Include="com.etsoo.ThirdPartyExtentions" Version="1.0.8" />
    <PackageReference Include="com.etsoo.WeiXin" Version="1.0.40" />
    <PackageReference Include="EfCore.SchemaCompare" Version="10.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.9" />
    <PackageReference Include="Microsoft.AspNetCore.SpaProxy">
      <Version>10.0.9</Version>
    </PackageReference>
	<PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="5.6.0" />
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.23.0" />
    <PackageReference Include="OpenTelemetry.Exporter.Console" Version="1.16.0" />
    <PackageReference Include="OpenTelemetry.Extensions.Hosting" Version="1.16.0" />
    <PackageReference Include="Swashbuckle.AspNetCore.SwaggerUI" Version="10.2.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\WebTemplates\WebTemplates.csproj" />
    <ProjectReference Include="..\platform.client\platform.client.esproj">
      <ReferenceOutputAssembly>false</ReferenceOutputAssembly>
    </ProjectReference>
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.zh-Hans.resx">
      <DependentUpon>Properties\Resources.resx</DependentUpon>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.zh-Hant.resx">
      <DependentUpon>Properties\Resources.resx</DependentUpon>
    </EmbeddedResource>
  </ItemGroup>

</Project>
