<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>82c1b486-7653-4980-93a1-7000968472fc</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    <DockerfileContext>..\..</DockerfileContext>
    <SpaRoot>..\platform.client</SpaRoot>
    <SpaProxyLaunchCommand>npm run dev</SpaProxyLaunchCommand>
    <SpaProxyServerUrl>https://localhost:9002</SpaProxyServerUrl>
    <PublishAot>false</PublishAot>
    <JsonSerializerIsReflectionEnabledByDefault>true</JsonSerializerIsReflectionEnabledByDefault>
  </PropertyGroup>

  <ItemGroup>
    <None Include="efpt.config.json.user" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="com.etsoo.AlipayApi" Version="1.0.9" />
    <PackageReference Include="com.etsoo.ApiProxy" Version="1.0.54" />
    <PackageReference Include="com.etsoo.BaiduApi" Version="1.0.20" />
    <PackageReference Include="com.etsoo.GarnetClient" Version="1.0.2" />
    <PackageReference Include="com.etsoo.GoogleApi" Version="1.0.39" />
    <PackageReference Include="com.etsoo.ImageUtils" Version="1.0.74" />
    <PackageReference Include="com.etsoo.Localization" Version="1.0.22" />
    <PackageReference Include="com.etsoo.MicrosoftApi" Version="1.0.11" />
    <PackageReference Include="com.etsoo.ThirdPartyExtentions" Version="1.0.3" />
    <PackageReference Include="com.etsoo.WeiXin" Version="1.0.40" />
    <PackageReference Include="EfCore.SchemaCompare" Version="8.2.0" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="8.0.12" />
    <PackageReference Include="Microsoft.AspNetCore.SpaProxy">
      <Version>8.0.12</Version>
    </PackageReference>
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.21.0" />
    <PackageReference Include="OpenTelemetry.Exporter.Console" Version="1.11.1" />
    <PackageReference Include="OpenTelemetry.Extensions.Hosting" Version="1.11.1" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="7.2.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\PlatformShared\PlatformShared.csproj" />
    <ProjectReference Include="..\platform.client\platform.client.esproj">
      <ReferenceOutputAssembly>false</ReferenceOutputAssembly>
    </ProjectReference>
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <Content Update="Templates\EmailCallback.cshtml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Update="Templates\EmailMemberInvitation.cshtml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Update="Templates\EmailRegistration.cshtml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Update="Templates\EmailVerification.cshtml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.zh-Hans.resx">
      <DependentUpon>Properties\Resources.resx</DependentUpon>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.zh-Hant.resx">
      <DependentUpon>Properties\Resources.resx</DependentUpon>
    </EmbeddedResource>
  </ItemGroup>

</Project>
