apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openobserve-pvc
  namespace: openobserve-system
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: openobserve
  namespace: openobserve-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openobserve
  template:
    metadata:
      labels:
        app: openobserve
    spec:
      containers:
        - name: openobserve
          image: openobserve/openobserve:v1.0.0-rc1
          ports:
            - containerPort: 5080
          env:
            - name: ZO_ROOT_USER_EMAIL
              valueFrom:
                secretKeyRef:
                  name: openobserve-secret
                  key: zo-root-user-email
            - name: ZO_ROOT_USER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: openobserve-secret
                  key: zo-root-user-password
          volumeMounts:
            - name: openobserve-data
              mountPath: /data
          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
            limits:
              memory: "2Gi"
              cpu: "2000m"
      volumes:
        - name: openobserve-data
          persistentVolumeClaim:
            claimName: openobserve-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: openobserve-service
  namespace: openobserve-system
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 5080
      targetPort: 5080
  selector:
    app: openobserve
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: openobserve-route
  namespace: openobserve-system
spec:
  parentRefs:
    - name: traefik-gateway
      namespace: ingress
  hostnames:
    - "log.etsoo.com"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: openobserve-service
          port: 5080
