apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base/platform

images:
  - name: smarterp/smarterp-platform
    newName: etsoo-registry.cn-qingdao.cr.aliyuncs.com/smarterp/smarterp-platform

secretGenerator:
  # 生成应用配置环境变量
  - name: smarterp-prod-secrets
    envs:
      - ../../../../secrets/platform.env.secrets

patches:
  # 仅 CN 注入 imagePullSecrets
  - target:
      kind: Deployment
      name: smarterp-platform
    patch: |-
      - op: add
        path: /spec/template/spec/imagePullSecrets
        value:
          - name: aliyun-acr-secret
