apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base/platform

secretGenerator:
  # 仅 CN 生成镜像凭据
  - name: registry-secret
    type: kubernetes.io/dockerconfigjson
    envs:
      - /etc/smarterp/.env.secrets

  # 生成应用配置环境变量
  - name: smarterp-prod-secrets
    envs:
      - /etc/smarterp/.env.secrets

patches:
  # 仅 CN 注入 imagePullSecrets
  - target:
      kind: Deployment
      name: platform
    patch: |-
      - op: add
        path: /spec/template/spec/imagePullSecrets
        value:
          - name: registry-secret
