apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: smarterp

resources:
  - ../../../base/shared
  - ../../../base/workercenter

images:
  - name: smarterp/smarterp-workercenter
    newName: etsoo-registry.cn-qingdao.cr.aliyuncs.com/smarterp/smarterp-workercenter

secretGenerator:
  # 生成应用配置环境变量
  - name: workercenter-secrets
    envs:
      - workercenter.env.secrets

patches:
  # 仅 CN 注入 imagePullSecrets
  - target:
      kind: Deployment
      name: smarterp-workercenter
    patch: |-
      - op: add
        path: /spec/template/spec/imagePullSecrets
        value:
          - name: aliyun-acr-secret
