//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Platform.Server.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Platform.Server.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invitation accepted.
        /// </summary>
        public static string MemberInvitationDone {
            get {
                return ResourceManager.GetString("MemberInvitationDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password cannot be less than 4 characters or more than 30 characters.
        /// </summary>
        public static string PasswordLengthInvalid {
            get {
                return ResourceManager.GetString("PasswordLengthInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User email password callback code.
        /// </summary>
        public static string UserCallbackEmailCode {
            get {
                return ResourceManager.GetString("UserCallbackEmailCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User SMS password callback code.
        /// </summary>
        public static string UserCallbackSMSCode {
            get {
                return ResourceManager.GetString("UserCallbackSMSCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only supports email and mobile number.
        /// </summary>
        public static string UserIdInvalid {
            get {
                return ResourceManager.GetString("UserIdInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User email registration code.
        /// </summary>
        public static string UserRegistrationEmailCode {
            get {
                return ResourceManager.GetString("UserRegistrationEmailCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User SMS registration code.
        /// </summary>
        public static string UserRegistrationSMSCode {
            get {
                return ResourceManager.GetString("UserRegistrationSMSCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User email address verification code.
        /// </summary>
        public static string UserVerificationEmailCode {
            get {
                return ResourceManager.GetString("UserVerificationEmailCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User mobile phone number verification code.
        /// </summary>
        public static string UserVerificationSMSCode {
            get {
                return ResourceManager.GetString("UserVerificationSMSCode", resourceCulture);
            }
        }
    }
}
