<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <SatelliteResourceLanguages>en;zh-Hans;zh-Hant</SatelliteResourceLanguages>
        <OutputType>Library</OutputType>
    </PropertyGroup>

	<PropertyGroup>
		<!-- Enable automatic template compilation before build -->
		<RazorEngineCore_EnableCompileTemplates>true</RazorEngineCore_EnableCompileTemplates>
		<RazorEngineCore_IncludeDebuggingInfo>false</RazorEngineCore_IncludeDebuggingInfo>
		<RazorEngineCore_TemplateDir>$(MSBuildProjectDirectory)\Templates</RazorEngineCore_TemplateDir>
	</PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\PlatformShared\PlatformShared.csproj" />
    </ItemGroup>

	<ItemGroup>
		<PackageReference Include="Etsoo.RazorEngineCore" Version="1.0.39" />
	</ItemGroup>

</Project>
