apiVersion: apps/v1
kind: Deployment
metadata:
  name: smarterp-coreapp
  namespace: smarterp
  labels:
    app: smarterp-coreapp
spec:
  replicas: {{ .Values.replicaCount | default 1 }}
  selector:
    matchLabels:
      app: smarterp-coreapp
  template:
    metadata:
      labels:
        app: smarterp-coreapp
    spec:
      {{- if .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml .Values.global.imagePullSecrets | nindent 8 }}
      {{- end }}
      containers:
        - name: smarterp-coreapp
          image: "{{ .Values.global.imageRegistry }}/smarterp-coreapp:{{ .Values.imageTag | default .Values.global.imageTag }}"
          ports:
            - containerPort: 8080
              name: http
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 10
          env:
            - name: ASPNETCORE_HTTP_PORTS
              value: "8080"
            - name: DOTNET_ENVIRONMENT
              value: "{{ .Values.global.DOTNET_ENVIRONMENT }}"
            - name: TZ
              value: "{{ .Values.global.TZ }}"
          envFrom:
            - secretRef:
                name: shared-secrets
            - secretRef:
                name: coreapp-secrets
          resources:
            requests:
              cpu: "10m"
              memory: "64Mi"
            limits:
              cpu: "1"
              memory: "2Gi"