apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: smarterp

resources:
  - ../../../base/shared
  - ../../../base/workercms

images:
  - name: smarterp/smarterp-workercms
    newName: ghcr.io/etsoo/smarterp-workercms

secretGenerator:
  # 生成应用配置环境变量
  - name: workercms-secrets
    envs:
      - workercms.env.secrets
