apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: smarterp

resources:
  - ../../../base/platform

images:
  - name: smarterp/smarterp-platform
    newName: ghcr.io/etsoo/smarterp-platform

secretGenerator:
  # 生成应用配置环境变量
  - name: platform-secrets
    envs:
      - platform.env.secrets

patches:
  - target:
      group: gateway.networking.k8s.io
      version: v1
      kind: HTTPRoute
      name: smarterp-platform-route
    patch: |-
      - op: replace
        path: /spec/hostnames/0
        value: "platform.etsoo.nz"
