apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: smarterp

resources:
  - ../../../base/admin

images:
  - name: smarterp/smarterp-admin
    newName: ghcr.io/etsoo/smarterp-admin

secretGenerator:
  # 生成应用配置环境变量
  - name: admin-secrets
    envs:
      - admin.env.secrets

patches:
  - target:
      group: gateway.networking.k8s.io
      version: v1
      kind: HTTPRoute
      name: smarterp-admin-route
    patch: |-
      - op: replace
        path: /spec/hostnames/0
        value: "admin.etsoo.nz"
