apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: smarterp

# Declaration of the Helm output file as a resource
# 声明引入脚本运行时生成的 Helm 输出文件
resources:
  - helm-output.yaml

# Generate secrets from the .env.secrets files
# 生成机密，路径指向 config/ 目录下的 .env.secrets 文件
secretGenerator:
  - name: shared-secrets
    envs:
      - ../config/shared.env.secrets

  - name: admin-secrets
    envs:
      - ../config/admin.env.secrets

  - name: coreapp-secrets
    envs:
      - ../config/coreapp.env.secrets

  - name: crm-secrets
    envs:
      - ../config/crm.env.secrets

  - name: platform-secrets
    envs:
      - ../config/platform.env.secrets

  - name: workercenter-secrets
    envs:
      - ../config/workercenter.env.secrets

  - name: workercms-secrets
    envs:
      - ../config/workercms.env.secrets
