apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: smarterp

resources:
  - ../../../base/coreapp

images:
  - name: smarterp/smarterp-coreapp
    newName: ghcr.io/etsoo/smarterp-coreapp

secretGenerator:
  # 生成应用配置环境变量
  - name: coreapp-secrets
    envs:
      - coreapp.env.secrets
