// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Platform.Server.Models;
using System;
using System.Collections.Generic;

#nullable disable

namespace Platform.Server.Models.Configurations
{
    public partial class CoreUserDeviceConfiguration : IEntityTypeConfiguration<CoreUserDevice>
    {
        public void Configure(EntityTypeBuilder<CoreUserDevice> entity)
        {
            entity.HasKey(e => e.Id).HasName("core_user_device_pkey");

            entity.ToTable("core_user_device");

            entity.Property(e => e.Id)
                .UseIdentityAlwaysColumn()
                .HasIdentityOptions(1001L, null, null, null, null, null)
                .HasColumnName("id");
            entity.Property(e => e.ClientId)
                .HasMaxLength(256)
                .HasColumnName("client_id");
            entity.Property(e => e.CoreUserId).HasColumnName("core_user_id");
            entity.Property(e => e.Creation)
                .HasDefaultValueSql("now()")
                .HasColumnName("creation");
            entity.Property(e => e.DeviceType).HasColumnName("device_type");
            entity.Property(e => e.LastLogin)
                .HasDefaultValueSql("now()")
                .HasColumnName("last_login");
            entity.Property(e => e.Name)
                .HasMaxLength(128)
                .HasColumnName("name");
            entity.Property(e => e.Timezone)
                .HasMaxLength(64)
                .HasColumnName("timezone");

            entity.HasOne(d => d.CoreUser).WithMany(p => p.CoreUserDevices)
                .HasForeignKey(d => d.CoreUserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("core_user_device_core_user_id_fkey");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<CoreUserDevice> entity);
    }
}
