// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Platform.Server.Models;
using System;
using System.Collections.Generic;

#nullable disable

namespace Platform.Server.Models.Configurations
{
    public partial class CoreDocumentConfiguration : IEntityTypeConfiguration<CoreDocument>
    {
        public void Configure(EntityTypeBuilder<CoreDocument> entity)
        {
            entity.HasKey(e => e.Id).HasName("core_document_pkey");

            entity.ToTable("core_document");

            entity.Property(e => e.Id)
                .UseIdentityAlwaysColumn()
                .HasColumnName("id");
            entity.Property(e => e.CoreOrganizationId).HasColumnName("core_organization_id");
            entity.Property(e => e.Cultures)
                .HasColumnType("character varying(20)[]")
                .HasColumnName("cultures");
            entity.Property(e => e.Kind)
                .HasMaxLength(20)
                .HasColumnName("kind");
            entity.Property(e => e.Parameters)
                .HasColumnType("jsonb")
                .HasColumnName("parameters");
            entity.Property(e => e.RefreshTime).HasColumnName("refresh_time");
            entity.Property(e => e.Template).HasColumnName("template");
            entity.Property(e => e.Title)
                .HasMaxLength(128)
                .HasColumnName("title");

            entity.HasOne(d => d.CoreOrganization).WithMany(p => p.CoreDocuments)
                .HasForeignKey(d => d.CoreOrganizationId)
                .HasConstraintName("core_document_core_organization_id_fkey");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<CoreDocument> entity);
    }
}
