// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Platform.Server.Models;
using System;
using System.Collections.Generic;

#nullable disable

namespace Platform.Server.Models.Configurations
{
    public partial class CoreOrganizationAppConfiguration : IEntityTypeConfiguration<CoreOrganizationApp>
    {
        public void Configure(EntityTypeBuilder<CoreOrganizationApp> entity)
        {
            entity.HasKey(e => e.Id).HasName("core_organization_app_pkey");

            entity.ToTable("core_organization_app");

            entity.Property(e => e.Id)
                .UseIdentityAlwaysColumn()
                .HasColumnName("id");
            entity.Property(e => e.AppKey)
                .HasMaxLength(128)
                .HasColumnName("app_key");
            entity.Property(e => e.AppSecret)
                .HasMaxLength(256)
                .HasColumnName("app_secret");
            entity.Property(e => e.CoreAppId).HasColumnName("core_app_id");
            entity.Property(e => e.CoreOrganizationId).HasColumnName("core_organization_id");
            entity.Property(e => e.Creation)
                .HasDefaultValueSql("now()")
                .HasColumnName("creation");
            entity.Property(e => e.Expiry).HasColumnName("expiry");
            entity.Property(e => e.LocalName)
                .HasMaxLength(128)
                .HasColumnName("local_name");
            entity.Property(e => e.LocalUrls)
                .HasColumnType("jsonb")
                .HasColumnName("local_urls");
            entity.Property(e => e.Status).HasColumnName("status");

            entity.HasOne(d => d.CoreApp).WithMany(p => p.CoreOrganizationApps)
                .HasForeignKey(d => d.CoreAppId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("core_organization_app_core_app_id_fkey");

            entity.HasOne(d => d.CoreOrganization).WithMany(p => p.CoreOrganizationApps)
                .HasForeignKey(d => d.CoreOrganizationId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("core_organization_app_core_organization_id_fkey");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<CoreOrganizationApp> entity);
    }
}
