// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Platform.Server.Models;
using System;
using System.Collections.Generic;

#nullable disable

namespace Platform.Server.Models.Configurations
{
    public partial class CoreAppConfiguration : IEntityTypeConfiguration<CoreApp>
    {
        public void Configure(EntityTypeBuilder<CoreApp> entity)
        {
            entity.HasKey(e => e.Id).HasName("core_app_pkey");

            entity.ToTable("core_app");

            entity.Property(e => e.Id)
                .ValueGeneratedNever()
                .HasColumnName("id");
            entity.Property(e => e.AppSecret)
                .HasMaxLength(256)
                .HasColumnName("app_secret");
            entity.Property(e => e.Creation)
                .HasDefaultValueSql("now()")
                .HasColumnName("creation");
            entity.Property(e => e.Enabled).HasColumnName("enabled");
            entity.Property(e => e.IdentityType).HasColumnName("identity_type");
            entity.Property(e => e.IsPublic).HasColumnName("is_public");
            entity.Property(e => e.Logo)
                .HasMaxLength(256)
                .HasColumnName("logo");
            entity.Property(e => e.Name)
                .HasMaxLength(128)
                .HasColumnName("name");
            entity.Property(e => e.RequireLocalUrl).HasColumnName("require_local_url");
            entity.Property(e => e.Urls)
                .HasColumnType("jsonb")
                .HasColumnName("urls");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<CoreApp> entity);
    }
}
