// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Platform.Server.Models;
using System;
using System.Collections.Generic;

#nullable disable

namespace Platform.Server.Models.Configurations
{
    public partial class CoreUserDeviceTokenConfiguration : IEntityTypeConfiguration<CoreUserDeviceToken>
    {
        public void Configure(EntityTypeBuilder<CoreUserDeviceToken> entity)
        {
            entity.HasKey(e => e.Id).HasName("core_user_device_token_pkey");

            entity.ToTable("core_user_device_token");

            entity.HasIndex(e => new { e.DeviceId, e.ResponseType, e.AppId, e.Token, e.Expiry }, "core_user_device_token_device_id_app_id_token_idx").HasAnnotation("Npgsql:StorageParameter:deduplicate_items", "true");

            entity.Property(e => e.Id)
                .UseIdentityAlwaysColumn()
                .HasColumnName("id");
            entity.Property(e => e.AppId).HasColumnName("app_id");
            entity.Property(e => e.Culture)
                .HasMaxLength(10)
                .HasColumnName("culture");
            entity.Property(e => e.Data)
                .HasColumnType("jsonb")
                .HasColumnName("data");
            entity.Property(e => e.DeviceId).HasColumnName("device_id");
            entity.Property(e => e.Expiry).HasColumnName("expiry");
            entity.Property(e => e.ResponseType).HasColumnName("response_type");
            entity.Property(e => e.Token)
                .HasMaxLength(256)
                .HasColumnName("token");

            entity.HasOne(d => d.App).WithMany(p => p.CoreUserDeviceTokens)
                .HasForeignKey(d => d.AppId)
                .HasConstraintName("core_user_device_token_app_id_fkey");

            entity.HasOne(d => d.Device).WithMany(p => p.CoreUserDeviceTokens)
                .HasForeignKey(d => d.DeviceId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("core_user_device_token_device_id_fkey");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<CoreUserDeviceToken> entity);
    }
}
