// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Platform.Server.Models;
using System;
using System.Collections.Generic;

#nullable disable

namespace Platform.Server.Models.Configurations
{
    public partial class CoreAuthCodeConfiguration : IEntityTypeConfiguration<CoreAuthCode>
    {
        public void Configure(EntityTypeBuilder<CoreAuthCode> entity)
        {
            entity.HasKey(e => e.Id).HasName("core_auth_code_pkey");

            entity.ToTable("core_auth_code");

            entity.Property(e => e.Id)
                .ValueGeneratedNever()
                .HasColumnName("id");
            entity.Property(e => e.Action).HasColumnName("action");
            entity.Property(e => e.Code)
                .HasMaxLength(256)
                .HasColumnName("code");
            entity.Property(e => e.CoreUserId).HasColumnName("core_user_id");
            entity.Property(e => e.Creation)
                .HasDefaultValueSql("now()")
                .HasColumnName("creation");
            entity.Property(e => e.Data)
                .HasColumnType("jsonb")
                .HasColumnName("data");
            entity.Property(e => e.Expiry).HasColumnName("expiry");
            entity.Property(e => e.Ip)
                .HasMaxLength(45)
                .HasColumnName("ip");
            entity.Property(e => e.Openid)
                .HasMaxLength(256)
                .HasColumnName("openid");
            entity.Property(e => e.Times).HasColumnName("times");

            entity.HasOne(d => d.CoreUser).WithMany(p => p.CoreAuthCodes)
                .HasForeignKey(d => d.CoreUserId)
                .HasConstraintName("core_auth_code_core_user_id_fkey");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<CoreAuthCode> entity);
    }
}
