// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Platform.Server.Models;
using System;
using System.Collections.Generic;

#nullable disable

namespace Platform.Server.Models.Configurations
{
    public partial class CoreUserConfiguration : IEntityTypeConfiguration<CoreUser>
    {
        public void Configure(EntityTypeBuilder<CoreUser> entity)
        {
            entity.HasKey(e => e.Id).HasName("core_user_pkey");

            entity.ToTable("core_user");

            entity.Property(e => e.Id)
                .HasIdentityOptions(1021L, null, null, null, null, null)
                .HasColumnName("id");
            entity.Property(e => e.Avatar)
                .HasMaxLength(256)
                .HasColumnName("avatar");
            entity.Property(e => e.Creation)
                .HasDefaultValueSql("now()")
                .HasColumnName("creation");
            entity.Property(e => e.FamilyName)
                .HasMaxLength(50)
                .HasColumnName("family_name");
            entity.Property(e => e.FrozenTime).HasColumnName("frozen_time");
            entity.Property(e => e.GivenName)
                .HasMaxLength(50)
                .HasColumnName("given_name");
            entity.Property(e => e.LatestAppIds).HasColumnName("latest_app_ids");
            entity.Property(e => e.LatestOrganizationIds).HasColumnName("latest_organization_ids");
            entity.Property(e => e.LatinFamilyName)
                .HasMaxLength(50)
                .HasColumnName("latin_family_name");
            entity.Property(e => e.LatinGivenName)
                .HasMaxLength(50)
                .HasColumnName("latin_given_name");
            entity.Property(e => e.Name)
                .HasMaxLength(128)
                .HasColumnName("name");
            entity.Property(e => e.Password)
                .HasMaxLength(128)
                .HasColumnName("password");
            entity.Property(e => e.Pin)
                .HasMaxLength(20)
                .HasColumnName("pin");
            entity.Property(e => e.PreferredName)
                .HasMaxLength(128)
                .HasColumnName("preferred_name");
            entity.Property(e => e.QueryKeyword)
                .HasMaxLength(30)
                .HasColumnName("query_keyword");
            entity.Property(e => e.Region)
                .HasMaxLength(2)
                .IsFixedLength()
                .HasColumnName("region");
            entity.Property(e => e.Status)
                .HasDefaultValue((short)0)
                .HasColumnName("status");
            entity.Property(e => e.Step).HasColumnName("step");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<CoreUser> entity);
    }
}
