// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Platform.Server.Models;
using System;
using System.Collections.Generic;

#nullable disable

namespace Platform.Server.Models.Configurations
{
    public partial class FeatureCultureConfiguration : IEntityTypeConfiguration<FeatureCulture>
    {
        public void Configure(EntityTypeBuilder<FeatureCulture> entity)
        {
            entity.HasKey(e => e.Id).HasName("feature_culture_pkey");

            entity.ToTable("feature_culture");

            entity.HasIndex(e => new { e.Key, e.Culture, e.CoreOrganizationId }, "feature_culture_key_culture_core_organization_id_id_title_d_idx")
                .IsUnique()
                .HasAnnotation("Npgsql:StorageParameter:deduplicate_items", "true");

            entity.Property(e => e.Id)
                .UseIdentityAlwaysColumn()
                .HasColumnName("id");
            entity.Property(e => e.CoreOrganizationId).HasColumnName("core_organization_id");
            entity.Property(e => e.Culture)
                .HasMaxLength(10)
                .HasColumnName("culture");
            entity.Property(e => e.Description)
                .HasMaxLength(2560)
                .HasColumnName("description");
            entity.Property(e => e.JsonData)
                .HasColumnType("jsonb")
                .HasColumnName("json_data");
            entity.Property(e => e.Key)
                .HasMaxLength(50)
                .HasColumnName("key");
            entity.Property(e => e.Title)
                .HasMaxLength(256)
                .HasColumnName("title");

            entity.HasOne(d => d.CoreOrganization).WithMany(p => p.FeatureCultures)
                .HasForeignKey(d => d.CoreOrganizationId)
                .HasConstraintName("feature_culture_core_organization_id_fkey");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<FeatureCulture> entity);
    }
}
