// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Platform.Server.Models;
using System;
using System.Collections.Generic;

#nullable disable

namespace Platform.Server.Models.Configurations
{
    public partial class FeatureKeywordConfiguration : IEntityTypeConfiguration<FeatureKeyword>
    {
        public void Configure(EntityTypeBuilder<FeatureKeyword> entity)
        {
            entity.HasKey(e => e.Id).HasName("feature_keyword_pkey");

            entity.ToTable("feature_keyword");

            entity.Property(e => e.Id)
                .UseIdentityAlwaysColumn()
                .HasColumnName("id");
            entity.Property(e => e.CoreOrganizationId).HasColumnName("core_organization_id");
            entity.Property(e => e.Kind).HasColumnName("kind");
            entity.Property(e => e.Tag)
                .HasMaxLength(128)
                .HasColumnName("tag");
            entity.Property(e => e.Total).HasColumnName("total");

            entity.HasOne(d => d.CoreOrganization).WithMany(p => p.FeatureKeywords)
                .HasForeignKey(d => d.CoreOrganizationId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("feature_keyword_core_organization_id_fkey");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<FeatureKeyword> entity);
    }
}
