// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Platform.Server.Models;
using System;
using System.Collections.Generic;

#nullable disable

namespace Platform.Server.Models.Configurations
{
    public partial class FinanceTransactionConfiguration : IEntityTypeConfiguration<FinanceTransaction>
    {
        public void Configure(EntityTypeBuilder<FinanceTransaction> entity)
        {
            entity.HasKey(e => e.Id).HasName("finance_transaction_pkey");

            entity.ToTable("finance_transaction");

            entity.Property(e => e.Id)
                .UseIdentityAlwaysColumn()
                .HasColumnName("id");
            entity.Property(e => e.AccountId).HasColumnName("account_id");
            entity.Property(e => e.Amount)
                .HasPrecision(18, 2)
                .HasColumnName("amount");
            entity.Property(e => e.AuthorId).HasColumnName("author_id");
            entity.Property(e => e.CoreOrganizationId).HasColumnName("core_organization_id");
            entity.Property(e => e.Creation)
                .HasDefaultValueSql("now()")
                .HasColumnName("creation");
            entity.Property(e => e.InnerRef).HasColumnName("inner_ref");
            entity.Property(e => e.Kind).HasColumnName("kind");
            entity.Property(e => e.OffsetId).HasColumnName("offset_id");
            entity.Property(e => e.OrderId).HasColumnName("order_id");
            entity.Property(e => e.ReferenceId)
                .HasMaxLength(30)
                .HasColumnName("reference_id");
            entity.Property(e => e.TargetAccountId).HasColumnName("target_account_id");
            entity.Property(e => e.TargetPersonId).HasColumnName("target_person_id");
            entity.Property(e => e.Times).HasColumnName("times");
            entity.Property(e => e.Title)
                .HasMaxLength(256)
                .HasColumnName("title");

            entity.HasOne(d => d.Account).WithMany(p => p.FinanceTransactionAccounts)
                .HasForeignKey(d => d.AccountId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("finance_transaction_account_id_fkey");

            entity.HasOne(d => d.Author).WithMany(p => p.FinanceTransactionAuthors)
                .HasForeignKey(d => d.AuthorId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("finance_transaction_author_id_fkey");

            entity.HasOne(d => d.CoreOrganization).WithMany(p => p.FinanceTransactions)
                .HasForeignKey(d => d.CoreOrganizationId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("finance_transaction_core_organization_id_fkey");

            entity.HasOne(d => d.Order).WithMany(p => p.FinanceTransactions)
                .HasForeignKey(d => d.OrderId)
                .HasConstraintName("finance_transaction_order_id_fkey");

            entity.HasOne(d => d.TargetAccount).WithMany(p => p.FinanceTransactionTargetAccounts)
                .HasForeignKey(d => d.TargetAccountId)
                .HasConstraintName("finance_transaction_target_account_id_fkey");

            entity.HasOne(d => d.TargetPerson).WithMany(p => p.FinanceTransactionTargetPeople)
                .HasForeignKey(d => d.TargetPersonId)
                .HasConstraintName("finance_transaction_target_person_id_fkey");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<FinanceTransaction> entity);
    }
}
