// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Platform.Server.Models;
using System;
using System.Collections.Generic;

#nullable disable

namespace Platform.Server.Models.Configurations
{
    public partial class OrderAddressConfiguration : IEntityTypeConfiguration<OrderAddress>
    {
        public void Configure(EntityTypeBuilder<OrderAddress> entity)
        {
            entity.HasKey(e => e.Id).HasName("order_address_pkey");

            entity.ToTable("order_address");

            entity.Property(e => e.Id)
                .UseIdentityAlwaysColumn()
                .HasIdentityOptions(1000L, null, null, null, null, null)
                .HasColumnName("id");
            entity.Property(e => e.City)
                .HasMaxLength(50)
                .HasColumnName("city");
            entity.Property(e => e.District)
                .HasMaxLength(50)
                .HasColumnName("district");
            entity.Property(e => e.FormattedAddress)
                .HasMaxLength(256)
                .HasColumnName("formatted_address");
            entity.Property(e => e.Kind).HasColumnName("kind");
            entity.Property(e => e.Location).HasColumnName("location");
            entity.Property(e => e.Name)
                .HasMaxLength(128)
                .HasColumnName("name");
            entity.Property(e => e.OrderId).HasColumnName("order_id");
            entity.Property(e => e.PlaceId)
                .HasMaxLength(30)
                .HasColumnName("place_id");
            entity.Property(e => e.PostalCode)
                .HasMaxLength(10)
                .HasColumnName("postal_code");
            entity.Property(e => e.Provider).HasColumnName("provider");
            entity.Property(e => e.Region)
                .HasMaxLength(2)
                .IsFixedLength()
                .HasColumnName("region");
            entity.Property(e => e.Route)
                .HasMaxLength(128)
                .HasColumnName("route");
            entity.Property(e => e.State)
                .HasMaxLength(50)
                .HasColumnName("state");
            entity.Property(e => e.Street)
                .HasMaxLength(128)
                .HasColumnName("street");

            entity.HasOne(d => d.Order).WithMany(p => p.OrderAddresses)
                .HasForeignKey(d => d.OrderId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("order_address_order_id_fkey");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<OrderAddress> entity);
    }
}
