// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Platform.Server.Models;
using System;
using System.Collections.Generic;

#nullable disable

namespace Platform.Server.Models.Configurations
{
    public partial class PermissionItemConfiguration : IEntityTypeConfiguration<PermissionItem>
    {
        public void Configure(EntityTypeBuilder<PermissionItem> entity)
        {
            entity.HasKey(e => e.Id).HasName("permission_item_pkey");

            entity.ToTable("permission_item");

            entity.HasIndex(e => new { e.Module, e.Name }, "permission_item_module_name_id_idx")
                .IsUnique()
                .HasAnnotation("Npgsql:StorageParameter:deduplicate_items", "true");

            entity.Property(e => e.Id)
                .ValueGeneratedNever()
                .HasColumnName("id");
            entity.Property(e => e.Module).HasColumnName("module");
            entity.Property(e => e.Name)
                .HasMaxLength(50)
                .HasColumnName("name");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<PermissionItem> entity);
    }
}
