// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Platform.Server.Models;
using System;
using System.Collections.Generic;

#nullable disable

namespace Platform.Server.Models.Configurations
{
    public partial class PersonInfoConfiguration : IEntityTypeConfiguration<PersonInfo>
    {
        public void Configure(EntityTypeBuilder<PersonInfo> entity)
        {
            entity.HasKey(e => e.Id).HasName("person_info_pkey");

            entity.ToTable("person_info");

            entity.Property(e => e.Id)
                .UseIdentityAlwaysColumn()
                .HasColumnName("id");
            entity.Property(e => e.Creation)
                .HasDefaultValueSql("now()")
                .HasColumnName("creation");
            entity.Property(e => e.Description)
                .HasMaxLength(256)
                .HasColumnName("description");
            entity.Property(e => e.Identifier)
                .HasMaxLength(256)
                .HasColumnName("identifier");
            entity.Property(e => e.IsDefault).HasColumnName("is_default");
            entity.Property(e => e.IsVerified).HasColumnName("is_verified");
            entity.Property(e => e.Kind).HasColumnName("kind");
            entity.Property(e => e.PersonId).HasColumnName("person_id");
            entity.Property(e => e.Subscribed).HasColumnName("subscribed");

            entity.HasOne(d => d.Person).WithMany(p => p.PersonInfos)
                .HasForeignKey(d => d.PersonId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("person_info_person_id_fkey");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<PersonInfo> entity);
    }
}
