// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Platform.Server.Models;
using System;
using System.Collections.Generic;

#nullable disable

namespace Platform.Server.Models.Configurations
{
    public partial class PersonProfileConfiguration : IEntityTypeConfiguration<PersonProfile>
    {
        public void Configure(EntityTypeBuilder<PersonProfile> entity)
        {
            entity.HasKey(e => e.Id).HasName("person_profile_pkey");

            entity.ToTable("person_profile");

            entity.Property(e => e.Id)
                .UseIdentityAlwaysColumn()
                .HasColumnName("id");
            entity.Property(e => e.Comment).HasColumnName("comment");
            entity.Property(e => e.CoreUserId).HasColumnName("core_user_id");
            entity.Property(e => e.Creation)
                .HasDefaultValueSql("now()")
                .HasColumnName("creation");
            entity.Property(e => e.Data)
                .HasColumnType("jsonb")
                .HasColumnName("data");
            entity.Property(e => e.HappenDate).HasColumnName("happen_date");
            entity.Property(e => e.HappenDateEnd).HasColumnName("happen_date_end");
            entity.Property(e => e.IndexKey)
                .HasMaxLength(30)
                .HasColumnName("index_key");
            entity.Property(e => e.Kind).HasColumnName("kind");
            entity.Property(e => e.Location)
                .HasMaxLength(256)
                .HasColumnName("location");
            entity.Property(e => e.LocationId).HasColumnName("location_id");
            entity.Property(e => e.OrderId).HasColumnName("order_id");
            entity.Property(e => e.PersonId).HasColumnName("person_id");
            entity.Property(e => e.Persons).HasColumnName("persons");
            entity.Property(e => e.Status)
                .HasDefaultValue((short)0)
                .HasColumnName("status");
            entity.Property(e => e.Title)
                .HasMaxLength(256)
                .HasColumnName("title");
            entity.Property(e => e.UserRole).HasColumnName("user_role");

            entity.HasOne(d => d.CoreUser).WithMany(p => p.PersonProfiles)
                .HasForeignKey(d => d.CoreUserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("person_profile_core_user_id_fkey");

            entity.HasOne(d => d.Order).WithMany(p => p.PersonProfiles)
                .HasForeignKey(d => d.OrderId)
                .HasConstraintName("person_profile_order_id_fkey");

            entity.HasOne(d => d.Person).WithMany(p => p.PersonProfiles)
                .HasForeignKey(d => d.PersonId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("person_profile_person_id_fkey");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<PersonProfile> entity);
    }
}
