// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Platform.Server.Models;
using System;
using System.Collections.Generic;

#nullable disable

namespace Platform.Server.Models.Configurations
{
    public partial class PersonProductConfiguration : IEntityTypeConfiguration<PersonProduct>
    {
        public void Configure(EntityTypeBuilder<PersonProduct> entity)
        {
            entity.HasKey(e => new { e.PersonId, e.ProductId }).HasName("person_product_pkey");

            entity.ToTable("person_product");

            entity.Property(e => e.PersonId).HasColumnName("person_id");
            entity.Property(e => e.ProductId).HasColumnName("product_id");
            entity.Property(e => e.AssignedId)
                .HasMaxLength(20)
                .HasColumnName("assigned_id");
            entity.Property(e => e.JsonData)
                .HasColumnType("jsonb")
                .HasColumnName("json_data");
            entity.Property(e => e.UpdatedTime)
                .HasDefaultValueSql("now()")
                .HasColumnName("updated_time");

            entity.HasOne(d => d.Person).WithMany(p => p.PersonProducts)
                .HasForeignKey(d => d.PersonId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("person_product_person_id_fkey");

            entity.HasOne(d => d.Product).WithMany(p => p.PersonProducts)
                .HasForeignKey(d => d.ProductId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("person_product_product_id_fkey");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<PersonProduct> entity);
    }
}
