// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Platform.Server.Models;
using System;
using System.Collections.Generic;

#nullable disable

namespace Platform.Server.Models.Configurations
{
    public partial class PersonAssetConfiguration : IEntityTypeConfiguration<PersonAsset>
    {
        public void Configure(EntityTypeBuilder<PersonAsset> entity)
        {
            entity.HasKey(e => e.Id).HasName("person_asset_pkey");

            entity.ToTable("person_asset");

            entity.Property(e => e.Id)
                .UseIdentityAlwaysColumn()
                .HasColumnName("id");
            entity.Property(e => e.Amount)
                .HasColumnType("money")
                .HasColumnName("amount");
            entity.Property(e => e.CoreOrganizationId).HasColumnName("core_organization_id");
            entity.Property(e => e.CoreUserId).HasColumnName("core_user_id");
            entity.Property(e => e.Creation)
                .HasDefaultValueSql("now()")
                .HasColumnName("creation");
            entity.Property(e => e.Data)
                .HasColumnType("jsonb")
                .HasColumnName("data");
            entity.Property(e => e.Description)
                .HasMaxLength(1280)
                .HasColumnName("description");
            entity.Property(e => e.Expiry).HasColumnName("expiry");
            entity.Property(e => e.HealthCheckSchedule).HasColumnName("health_check_schedule");
            entity.Property(e => e.HealthCheckUrl)
                .HasMaxLength(1280)
                .HasColumnName("health_check_url");
            entity.Property(e => e.PersonId).HasColumnName("person_id");
            entity.Property(e => e.ProductId).HasColumnName("product_id");
            entity.Property(e => e.Qty)
                .HasDefaultValue((short)1)
                .HasColumnName("qty");
            entity.Property(e => e.SensitiveData)
                .HasMaxLength(1280)
                .HasColumnName("sensitive_data");
            entity.Property(e => e.Sn)
                .HasMaxLength(256)
                .HasColumnName("sn");
            entity.Property(e => e.Status)
                .HasDefaultValue((short)0)
                .HasColumnName("status");
            entity.Property(e => e.SupplierId).HasColumnName("supplier_id");
            entity.Property(e => e.Times).HasColumnName("times");
            entity.Property(e => e.Title)
                .HasMaxLength(128)
                .HasColumnName("title");

            entity.HasOne(d => d.CoreOrganization).WithMany(p => p.PersonAssets)
                .HasForeignKey(d => d.CoreOrganizationId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("person_asset_core_organization_id_fkey");

            entity.HasOne(d => d.CoreUser).WithMany(p => p.PersonAssets)
                .HasForeignKey(d => d.CoreUserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("person_asset_core_user_id_fkey");

            entity.HasOne(d => d.Person).WithMany(p => p.PersonAssetPeople)
                .HasForeignKey(d => d.PersonId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("person_asset_person_id_fkey");

            entity.HasOne(d => d.Product).WithMany(p => p.PersonAssets)
                .HasForeignKey(d => d.ProductId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("person_asset_product_id_fkey");

            entity.HasOne(d => d.Supplier).WithMany(p => p.PersonAssetSuppliers)
                .HasForeignKey(d => d.SupplierId)
                .HasConstraintName("person_asset_supplier_id_fkey");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<PersonAsset> entity);
    }
}
