// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Platform.Server.Models;
using System;
using System.Collections.Generic;

#nullable disable

namespace Platform.Server.Models.Configurations
{
    public partial class PersonConfiguration : IEntityTypeConfiguration<Person>
    {
        public void Configure(EntityTypeBuilder<Person> entity)
        {
            entity.HasKey(e => e.Id).HasName("person_pkey");

            entity.ToTable("person");

            entity.Property(e => e.Id)
                .UseIdentityAlwaysColumn()
                .HasIdentityOptions(1001L, null, null, null, null, null)
                .HasColumnName("id");
            entity.Property(e => e.AddressId).HasColumnName("address_id");
            entity.Property(e => e.AssignedId)
                .HasMaxLength(20)
                .HasColumnName("assigned_id");
            entity.Property(e => e.Avatar)
                .HasMaxLength(256)
                .HasColumnName("avatar");
            entity.Property(e => e.Birthday).HasColumnName("birthday");
            entity.Property(e => e.CategoryIds).HasColumnName("category_ids");
            entity.Property(e => e.CoreOrganizationId).HasColumnName("core_organization_id");
            entity.Property(e => e.CoreUserId).HasColumnName("core_user_id");
            entity.Property(e => e.Creation)
                .HasDefaultValueSql("now()")
                .HasColumnName("creation");
            entity.Property(e => e.Cultures)
                .HasColumnType("character varying(10)[]")
                .HasColumnName("cultures");
            entity.Property(e => e.Currencies)
                .HasColumnType("character(3)[]")
                .HasColumnName("currencies");
            entity.Property(e => e.Data)
                .HasColumnType("jsonb")
                .HasColumnName("data");
            entity.Property(e => e.Degree).HasColumnName("degree");
            entity.Property(e => e.Description)
                .HasMaxLength(1280)
                .HasColumnName("description");
            entity.Property(e => e.Education).HasColumnName("education");
            entity.Property(e => e.Ethnicity)
                .HasMaxLength(50)
                .HasColumnName("ethnicity");
            entity.Property(e => e.Expiry).HasColumnName("expiry");
            entity.Property(e => e.FamilyName)
                .HasMaxLength(50)
                .HasColumnName("family_name");
            entity.Property(e => e.Gender)
                .HasMaxLength(1)
                .HasColumnName("gender");
            entity.Property(e => e.GivenName)
                .HasMaxLength(50)
                .HasColumnName("given_name");
            entity.Property(e => e.Height).HasColumnName("height");
            entity.Property(e => e.IdentityType).HasColumnName("identity_type");
            entity.Property(e => e.InviterId).HasColumnName("inviter_id");
            entity.Property(e => e.IsLegalPerson)
                .HasDefaultValue(false)
                .HasColumnName("is_legal_person");
            entity.Property(e => e.JobTitle)
                .HasMaxLength(50)
                .HasColumnName("job_title");
            entity.Property(e => e.LatinFamilyName)
                .HasMaxLength(50)
                .HasColumnName("latin_family_name");
            entity.Property(e => e.LatinGivenName)
                .HasMaxLength(50)
                .HasColumnName("latin_given_name");
            entity.Property(e => e.MaritalStatus).HasColumnName("marital_status");
            entity.Property(e => e.Name)
                .HasMaxLength(128)
                .HasColumnName("name");
            entity.Property(e => e.OrganizationId).HasColumnName("organization_id");
            entity.Property(e => e.OwnerId).HasColumnName("owner_id");
            entity.Property(e => e.OwnerRelation).HasColumnName("owner_relation");
            entity.Property(e => e.PoliticalStatus)
                .HasMaxLength(50)
                .HasColumnName("political_status");
            entity.Property(e => e.PreferredName)
                .HasMaxLength(128)
                .HasColumnName("preferred_name");
            entity.Property(e => e.QueryKeyword)
                .HasMaxLength(30)
                .HasColumnName("query_keyword");
            entity.Property(e => e.RefreshTime)
                .HasDefaultValueSql("now()")
                .HasColumnName("refresh_time");
            entity.Property(e => e.Regions)
                .HasColumnType("character(2)[]")
                .HasColumnName("regions");
            entity.Property(e => e.ReportTo).HasColumnName("report_to");
            entity.Property(e => e.Status)
                .HasDefaultValue((short)0)
                .HasColumnName("status");
            entity.Property(e => e.Title).HasColumnName("title");
            entity.Property(e => e.Uid)
                .HasDefaultValueSql("gen_random_uuid()")
                .HasColumnName("uid");
            entity.Property(e => e.UserRole).HasColumnName("user_role");
            entity.Property(e => e.Weight)
                .HasPrecision(6, 2)
                .HasColumnName("weight");

            entity.HasOne(d => d.Address).WithMany(p => p.People)
                .HasForeignKey(d => d.AddressId)
                .HasConstraintName("person_address_id_fkey");

            entity.HasOne(d => d.CoreOrganization).WithMany(p => p.PersonCoreOrganizations)
                .HasForeignKey(d => d.CoreOrganizationId)
                .HasConstraintName("person_core_organization_id_fkey");

            entity.HasOne(d => d.CoreUser).WithMany(p => p.PersonCoreUsers)
                .HasForeignKey(d => d.CoreUserId)
                .HasConstraintName("person_core_user_id_fkey");

            entity.HasOne(d => d.Inviter).WithMany(p => p.PersonInviters)
                .HasForeignKey(d => d.InviterId)
                .HasConstraintName("person_inviter_id_fkey");

            entity.HasOne(d => d.Organization).WithMany(p => p.PersonOrganizations)
                .HasForeignKey(d => d.OrganizationId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("person_organization_id_fkey");

            entity.HasOne(d => d.Owner).WithMany(p => p.InverseOwner)
                .HasForeignKey(d => d.OwnerId)
                .HasConstraintName("person_owner_id_fkey");

            entity.HasOne(d => d.ReportToNavigation).WithMany(p => p.InverseReportToNavigation)
                .HasForeignKey(d => d.ReportTo)
                .HasConstraintName("person_report_to_fkey");

            entity.HasMany(d => d.Addresses).WithMany(p => p.PeopleNavigation)
                .UsingEntity<Dictionary<string, object>>(
                    "PersonAddress",
                    r => r.HasOne<Address>().WithMany()
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.ClientSetNull)
                        .HasConstraintName("person_address_address_id_fkey"),
                    l => l.HasOne<Person>().WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.ClientSetNull)
                        .HasConstraintName("person_address_person_id_fkey"),
                    j =>
                    {
                        j.HasKey("PersonId", "AddressId").HasName("person_address_pkey");
                        j.ToTable("person_address");
                        j.IndexerProperty<long>("PersonId").HasColumnName("person_id");
                        j.IndexerProperty<int>("AddressId").HasColumnName("address_id");
                    });

            entity.HasMany(d => d.CoreUsers).WithMany(p => p.People)
                .UsingEntity<Dictionary<string, object>>(
                    "PersonFavorite",
                    r => r.HasOne<CoreUser>().WithMany()
                        .HasForeignKey("CoreUserId")
                        .OnDelete(DeleteBehavior.ClientSetNull)
                        .HasConstraintName("person_favorite_core_user_id_fkey"),
                    l => l.HasOne<Person>().WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.ClientSetNull)
                        .HasConstraintName("person_favorite_person_id_fkey"),
                    j =>
                    {
                        j.HasKey("PersonId", "CoreUserId").HasName("person_favorite_pkey");
                        j.ToTable("person_favorite");
                        j.IndexerProperty<long>("PersonId").HasColumnName("person_id");
                        j.IndexerProperty<int>("CoreUserId").HasColumnName("core_user_id");
                    });

            entity.HasMany(d => d.FeatureKeywords).WithMany(p => p.People)
                .UsingEntity<Dictionary<string, object>>(
                    "PersonKeyword",
                    r => r.HasOne<FeatureKeyword>().WithMany()
                        .HasForeignKey("FeatureKeywordId")
                        .OnDelete(DeleteBehavior.ClientSetNull)
                        .HasConstraintName("person_keyword_feature_keyword_id_fkey"),
                    l => l.HasOne<Person>().WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.ClientSetNull)
                        .HasConstraintName("person_keyword_person_id_fkey"),
                    j =>
                    {
                        j.HasKey("PersonId", "FeatureKeywordId").HasName("person_keyword_pkey");
                        j.ToTable("person_keyword");
                        j.IndexerProperty<long>("PersonId").HasColumnName("person_id");
                        j.IndexerProperty<int>("FeatureKeywordId").HasColumnName("feature_keyword_id");
                    });

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Person> entity);
    }
}
