// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Platform.Server.Models;
using System;
using System.Collections.Generic;

#nullable disable

namespace Platform.Server.Models.Configurations
{
    public partial class PersonPermissionItemConfiguration : IEntityTypeConfiguration<PersonPermissionItem>
    {
        public void Configure(EntityTypeBuilder<PersonPermissionItem> entity)
        {
            entity.HasKey(e => new { e.PersonId, e.PermissionItemId }).HasName("person_permission_item_pkey");

            entity.ToTable("person_permission_item");

            entity.Property(e => e.PersonId).HasColumnName("person_id");
            entity.Property(e => e.PermissionItemId).HasColumnName("permission_item_id");

            entity.HasOne(d => d.PermissionItem).WithMany(p => p.PersonPermissionItems)
                .HasForeignKey(d => d.PermissionItemId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("person_permission_item_permission_item_id_fkey");

            entity.HasOne(d => d.Person).WithMany(p => p.PersonPermissionItems)
                .HasForeignKey(d => d.PersonId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("person_permission_item_person_id_fkey");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<PersonPermissionItem> entity);
    }
}
