// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Platform.Server.Models;
using System;
using System.Collections.Generic;

#nullable disable

namespace Platform.Server.Models.Configurations
{
    public partial class PersonProfileLinkConfiguration : IEntityTypeConfiguration<PersonProfileLink>
    {
        public void Configure(EntityTypeBuilder<PersonProfileLink> entity)
        {
            entity.HasKey(e => e.Id).HasName("person_profile_link_pkey");

            entity.ToTable("person_profile_link");

            entity.Property(e => e.Id)
                .UseIdentityAlwaysColumn()
                .HasIdentityOptions(null, null, null, 2147483647L, null, null)
                .HasColumnName("id");
            entity.Property(e => e.Content).HasColumnName("content");
            entity.Property(e => e.Creation)
                .HasDefaultValueSql("now()")
                .HasColumnName("creation");
            entity.Property(e => e.Kind).HasColumnName("kind");
            entity.Property(e => e.ProfileId).HasColumnName("profile_id");
            entity.Property(e => e.TargetProfileId).HasColumnName("target_profile_id");
            entity.Property(e => e.UserId).HasColumnName("user_id");

            entity.HasOne(d => d.Profile).WithMany(p => p.PersonProfileLinkProfiles)
                .HasForeignKey(d => d.ProfileId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("person_profile_link_profile_id_fkey");

            entity.HasOne(d => d.TargetProfile).WithMany(p => p.PersonProfileLinkTargetProfiles)
                .HasForeignKey(d => d.TargetProfileId)
                .HasConstraintName("person_profile_link_target_profile_id_fkey");

            entity.HasOne(d => d.User).WithMany(p => p.PersonProfileLinks)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("person_profile_link_user_id_fkey");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<PersonProfileLink> entity);
    }
}
