// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Platform.Server.Models;
using System;
using System.Collections.Generic;

#nullable disable

namespace Platform.Server.Models.Configurations
{
    public partial class ProductPriceConfiguration : IEntityTypeConfiguration<ProductPrice>
    {
        public void Configure(EntityTypeBuilder<ProductPrice> entity)
        {
            entity.HasKey(e => new { e.ProductId, e.Currency }).HasName("product_price_pkey");

            entity.ToTable("product_price");

            entity.Property(e => e.ProductId).HasColumnName("product_id");
            entity.Property(e => e.Currency)
                .HasMaxLength(3)
                .IsFixedLength()
                .HasColumnName("currency");
            entity.Property(e => e.ChannelPrice)
                .HasPrecision(18, 2)
                .HasColumnName("channel_price");
            entity.Property(e => e.CostPrice)
                .HasPrecision(18, 2)
                .HasColumnName("cost_price");
            entity.Property(e => e.Creation)
                .HasDefaultValueSql("now()")
                .HasColumnName("creation");
            entity.Property(e => e.PromotionPrice)
                .HasPrecision(18, 2)
                .HasColumnName("promotion_price");
            entity.Property(e => e.RetailPrice)
                .HasPrecision(18, 2)
                .HasColumnName("retail_price");

            entity.HasOne(d => d.Product).WithMany(p => p.ProductPrices)
                .HasForeignKey(d => d.ProductId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("product_price_product_id_fkey");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<ProductPrice> entity);
    }
}
