// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Platform.Server.Models;
using System;
using System.Collections.Generic;

#nullable disable

namespace Platform.Server.Models.Configurations
{
    public partial class ProductCultureConfiguration : IEntityTypeConfiguration<ProductCulture>
    {
        public void Configure(EntityTypeBuilder<ProductCulture> entity)
        {
            entity.HasKey(e => new { e.ProductId, e.Culture }).HasName("product_culture_pkey");

            entity.ToTable("product_culture");

            entity.Property(e => e.ProductId).HasColumnName("product_id");
            entity.Property(e => e.Culture)
                .HasMaxLength(10)
                .HasColumnName("culture");
            entity.Property(e => e.Data)
                .HasColumnType("jsonb")
                .HasColumnName("data");
            entity.Property(e => e.Description)
                .HasMaxLength(2560)
                .HasColumnName("description");
            entity.Property(e => e.Name)
                .HasMaxLength(256)
                .HasColumnName("name");

            entity.HasOne(d => d.Product).WithMany(p => p.ProductCultures)
                .HasForeignKey(d => d.ProductId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("product_culture_product_id_fkey");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<ProductCulture> entity);
    }
}
