// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Platform.Server.Models;
using System;
using System.Collections.Generic;

#nullable disable

namespace Platform.Server.Models.Configurations
{
    public partial class ProductBomConfiguration : IEntityTypeConfiguration<ProductBom>
    {
        public void Configure(EntityTypeBuilder<ProductBom> entity)
        {
            entity.HasKey(e => e.Id).HasName("product_bom_pkey");

            entity.ToTable("product_bom");

            entity.Property(e => e.Id)
                .UseIdentityAlwaysColumn()
                .HasIdentityOptions(1000L, null, null, null, null, null)
                .HasColumnName("id");
            entity.Property(e => e.ParentId).HasColumnName("parent_id");
            entity.Property(e => e.ProductId).HasColumnName("product_id");
            entity.Property(e => e.Qty)
                .HasPrecision(15, 2)
                .HasColumnName("qty");

            entity.HasOne(d => d.Parent).WithMany(p => p.ProductBomParents)
                .HasForeignKey(d => d.ParentId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("product_bom_parent_id_fkey");

            entity.HasOne(d => d.Product).WithMany(p => p.ProductBomProducts)
                .HasForeignKey(d => d.ProductId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("product_bom_product_id_fkey");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<ProductBom> entity);
    }
}
