// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Platform.Server.Models;
using System;
using System.Collections.Generic;

#nullable disable

namespace Platform.Server.Models.Configurations
{
    public partial class ProductUnitConfiguration : IEntityTypeConfiguration<ProductUnit>
    {
        public void Configure(EntityTypeBuilder<ProductUnit> entity)
        {
            entity.HasKey(e => e.Id).HasName("product_unit_pkey");

            entity.ToTable("product_unit");

            entity.Property(e => e.Id)
                .UseIdentityAlwaysColumn()
                .HasColumnName("id");
            entity.Property(e => e.CoreOrganizationId).HasColumnName("core_organization_id");
            entity.Property(e => e.Name)
                .HasMaxLength(20)
                .HasColumnName("name");
            entity.Property(e => e.OrderIndex).HasColumnName("order_index");

            entity.HasOne(d => d.CoreOrganization).WithMany(p => p.ProductUnits)
                .HasForeignKey(d => d.CoreOrganizationId)
                .HasConstraintName("product_unit_core_organization_id_fkey");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<ProductUnit> entity);
    }
}
