// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Platform.Server.Models;
using System;
using System.Collections.Generic;

#nullable disable

namespace Platform.Server.Models.Configurations
{
    public partial class ProductConfiguration : IEntityTypeConfiguration<Product>
    {
        public void Configure(EntityTypeBuilder<Product> entity)
        {
            entity.HasKey(e => e.Id).HasName("product_pkey");

            entity.ToTable("product");

            entity.Property(e => e.Id)
                .UseIdentityAlwaysColumn()
                .HasIdentityOptions(2001L, null, null, null, null, null)
                .HasColumnName("id");
            entity.Property(e => e.AssetQty).HasColumnName("asset_qty");
            entity.Property(e => e.AssetUnit).HasColumnName("asset_unit");
            entity.Property(e => e.CapQty)
                .HasPrecision(12, 2)
                .HasColumnName("cap_qty");
            entity.Property(e => e.CategoryIds).HasColumnName("category_ids");
            entity.Property(e => e.CoreOrganizationId).HasColumnName("core_organization_id");
            entity.Property(e => e.Creation)
                .HasDefaultValueSql("now()")
                .HasColumnName("creation");
            entity.Property(e => e.Data)
                .HasColumnType("jsonb")
                .HasColumnName("data");
            entity.Property(e => e.Description)
                .HasMaxLength(2560)
                .HasColumnName("description");
            entity.Property(e => e.ForeignName)
                .HasMaxLength(256)
                .HasColumnName("foreign_name");
            entity.Property(e => e.InventoryWay).HasColumnName("inventory_way");
            entity.Property(e => e.Logo)
                .HasMaxLength(256)
                .HasColumnName("logo");
            entity.Property(e => e.MinQty)
                .HasPrecision(6, 2)
                .HasColumnName("min_qty");
            entity.Property(e => e.Name)
                .HasMaxLength(256)
                .HasColumnName("name");
            entity.Property(e => e.OrderIndex).HasColumnName("order_index");
            entity.Property(e => e.QueryKeyword)
                .HasMaxLength(30)
                .HasColumnName("query_keyword");
            entity.Property(e => e.Scope).HasColumnName("scope");
            entity.Property(e => e.Status).HasColumnName("status");
            entity.Property(e => e.StepQty)
                .HasPrecision(6, 2)
                .HasColumnName("step_qty");
            entity.Property(e => e.Tags).HasColumnName("tags");
            entity.Property(e => e.UnitId).HasColumnName("unit_id");
            entity.Property(e => e.Usage).HasColumnName("usage");

            entity.HasOne(d => d.CoreOrganization).WithMany(p => p.Products)
                .HasForeignKey(d => d.CoreOrganizationId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("product_core_organization_id_fkey");

            entity.HasOne(d => d.Unit).WithMany(p => p.Products)
                .HasForeignKey(d => d.UnitId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("product_unit_id_fkey");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Product> entity);
    }
}
