// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Platform.Server.Models;
using System;
using System.Collections.Generic;

#nullable disable

namespace Platform.Server.Models.Configurations
{
    public partial class ProductConfiguration : IEntityTypeConfiguration<Product>
    {
        public void Configure(EntityTypeBuilder<Product> entity)
        {
            entity.HasKey(e => e.Id).HasName("product_pkey");

            entity.ToTable("product");

            entity.Property(e => e.Id)
                .UseIdentityAlwaysColumn()
                .HasIdentityOptions(2001L, null, null, null, null, null)
                .HasColumnName("id");
            entity.Property(e => e.AssetQty).HasColumnName("asset_qty");
            entity.Property(e => e.AssetUnit).HasColumnName("asset_unit");
            entity.Property(e => e.CapQty)
                .HasPrecision(12, 2)
                .HasColumnName("cap_qty");
            entity.Property(e => e.CategoryIds).HasColumnName("category_ids");
            entity.Property(e => e.CoreOrganizationId).HasColumnName("core_organization_id");
            entity.Property(e => e.Creation)
                .HasDefaultValueSql("now()")
                .HasColumnName("creation");
            entity.Property(e => e.Data)
                .HasColumnType("jsonb")
                .HasColumnName("data");
            entity.Property(e => e.Description)
                .HasMaxLength(2560)
                .HasColumnName("description");
            entity.Property(e => e.ForeignName)
                .HasMaxLength(256)
                .HasColumnName("foreign_name");
            entity.Property(e => e.InventoryWay)
                .HasDefaultValue((short)0)
                .HasColumnName("inventory_way");
            entity.Property(e => e.Logo)
                .HasMaxLength(256)
                .HasColumnName("logo");
            entity.Property(e => e.MinQty)
                .HasPrecision(6, 2)
                .HasColumnName("min_qty");
            entity.Property(e => e.Name)
                .HasMaxLength(256)
                .HasColumnName("name");
            entity.Property(e => e.OrderIndex)
                .HasDefaultValue((short)0)
                .HasColumnName("order_index");
            entity.Property(e => e.QueryKeyword)
                .HasMaxLength(30)
                .HasColumnName("query_keyword");
            entity.Property(e => e.Scope).HasColumnName("scope");
            entity.Property(e => e.Status)
                .HasDefaultValue((short)0)
                .HasColumnName("status");
            entity.Property(e => e.StepQty)
                .HasPrecision(6, 2)
                .HasColumnName("step_qty");
            entity.Property(e => e.UnitId).HasColumnName("unit_id");
            entity.Property(e => e.Usage).HasColumnName("usage");

            entity.HasOne(d => d.CoreOrganization).WithMany(p => p.Products)
                .HasForeignKey(d => d.CoreOrganizationId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("product_core_organization_id_fkey");

            entity.HasOne(d => d.Unit).WithMany(p => p.Products)
                .HasForeignKey(d => d.UnitId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("product_unit_id_fkey");

            entity.HasMany(d => d.CoreUsers).WithMany(p => p.Products)
                .UsingEntity<Dictionary<string, object>>(
                    "ProductFavorite",
                    r => r.HasOne<CoreUser>().WithMany()
                        .HasForeignKey("CoreUserId")
                        .OnDelete(DeleteBehavior.ClientSetNull)
                        .HasConstraintName("product_favorite_core_user_id_fkey"),
                    l => l.HasOne<Product>().WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.ClientSetNull)
                        .HasConstraintName("product_favorite_product_id_fkey"),
                    j =>
                    {
                        j.HasKey("ProductId", "CoreUserId").HasName("product_favorite_pkey");
                        j.ToTable("product_favorite");
                        j.IndexerProperty<int>("ProductId").HasColumnName("product_id");
                        j.IndexerProperty<int>("CoreUserId").HasColumnName("core_user_id");
                    });

            entity.HasMany(d => d.FeatureKeywords).WithMany(p => p.Products)
                .UsingEntity<Dictionary<string, object>>(
                    "ProductKeyword",
                    r => r.HasOne<FeatureKeyword>().WithMany()
                        .HasForeignKey("FeatureKeywordId")
                        .OnDelete(DeleteBehavior.ClientSetNull)
                        .HasConstraintName("product_keyword_feature_keyword_id_fkey"),
                    l => l.HasOne<Product>().WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.ClientSetNull)
                        .HasConstraintName("product_keyword_product_id_fkey"),
                    j =>
                    {
                        j.HasKey("ProductId", "FeatureKeywordId").HasName("product_keyword_pkey");
                        j.ToTable("product_keyword");
                        j.IndexerProperty<int>("ProductId").HasColumnName("product_id");
                        j.IndexerProperty<int>("FeatureKeywordId").HasColumnName("feature_keyword_id");
                    });

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Product> entity);
    }
}
