// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Platform.Server.Models;
using System;
using System.Collections.Generic;

#nullable disable

namespace Platform.Server.Models.Configurations
{
    public partial class PromotionConfiguration : IEntityTypeConfiguration<Promotion>
    {
        public void Configure(EntityTypeBuilder<Promotion> entity)
        {
            entity.HasKey(e => e.Id).HasName("promotion_pkey");

            entity.ToTable("promotion");

            entity.Property(e => e.Id)
                .UseIdentityAlwaysColumn()
                .HasIdentityOptions(2001L, null, null, null, null, null)
                .HasColumnName("id");
            entity.Property(e => e.Code).HasColumnName("code");
            entity.Property(e => e.CoreOrganizationId).HasColumnName("core_organization_id");
            entity.Property(e => e.Coupons).HasColumnName("coupons");
            entity.Property(e => e.Creation)
                .HasDefaultValueSql("now()")
                .HasColumnName("creation");
            entity.Property(e => e.Currency)
                .HasMaxLength(3)
                .IsFixedLength()
                .HasColumnName("currency");
            entity.Property(e => e.Discount).HasColumnName("discount");
            entity.Property(e => e.MinAmount)
                .HasColumnType("money")
                .HasColumnName("min_amount");
            entity.Property(e => e.OrderIndex).HasColumnName("order_index");
            entity.Property(e => e.PersonCategoryId).HasColumnName("person_category_id");
            entity.Property(e => e.PersonId).HasColumnName("person_id");
            entity.Property(e => e.ProductCategoryId).HasColumnName("product_category_id");
            entity.Property(e => e.ProductId).HasColumnName("product_id");
            entity.Property(e => e.Stackable).HasColumnName("stackable");
            entity.Property(e => e.Status).HasColumnName("status");
            entity.Property(e => e.Title)
                .HasMaxLength(128)
                .HasColumnName("title");
            entity.Property(e => e.ValidEnd).HasColumnName("valid_end");
            entity.Property(e => e.ValidStart).HasColumnName("valid_start");

            entity.HasOne(d => d.CoreOrganization).WithMany(p => p.Promotions)
                .HasForeignKey(d => d.CoreOrganizationId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("promotion_core_organization_id_fkey");

            entity.HasOne(d => d.PersonCategory).WithMany(p => p.Promotions)
                .HasForeignKey(d => d.PersonCategoryId)
                .HasConstraintName("promotion_person_category_id_fkey");

            entity.HasOne(d => d.Person).WithMany(p => p.Promotions)
                .HasForeignKey(d => d.PersonId)
                .HasConstraintName("promotion_person_id_fkey");

            entity.HasOne(d => d.ProductCategory).WithMany(p => p.Promotions)
                .HasForeignKey(d => d.ProductCategoryId)
                .HasConstraintName("promotion_product_category_id_fkey");

            entity.HasOne(d => d.Product).WithMany(p => p.Promotions)
                .HasForeignKey(d => d.ProductId)
                .HasConstraintName("promotion_product_id_fkey");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Promotion> entity);
    }
}
