// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Platform.Server.Models;
using System;
using System.Collections.Generic;

#nullable disable

namespace Platform.Server.Models.Configurations
{
    public partial class SettingCrmConfiguration : IEntityTypeConfiguration<SettingCrm>
    {
        public void Configure(EntityTypeBuilder<SettingCrm> entity)
        {
            entity.HasKey(e => e.Id).HasName("setting_crm_pkey");

            entity.ToTable("setting_crm");

            entity.Property(e => e.Id)
                .ValueGeneratedNever()
                .HasColumnName("id");
            entity.Property(e => e.AssetExpirationNotice).HasColumnName("asset_expiration_notice");
            entity.Property(e => e.Cultures)
                .HasColumnType("character varying(10)[]")
                .HasColumnName("cultures");
            entity.Property(e => e.Currencies)
                .HasColumnType("character(3)[]")
                .HasColumnName("currencies");
            entity.Property(e => e.HasInventory).HasColumnName("has_inventory");
            entity.Property(e => e.MainCustomerType).HasColumnName("main_customer_type");
            entity.Property(e => e.OrderDailyReportHour).HasColumnName("order_daily_report_hour");
            entity.Property(e => e.OrderMonthlyReportEnabled).HasColumnName("order_monthly_report_enabled");
            entity.Property(e => e.PersonId).HasColumnName("person_id");
            entity.Property(e => e.SupplierCurrencies)
                .HasColumnType("character(3)[]")
                .HasColumnName("supplier_currencies");
            entity.Property(e => e.TaxRate)
                .HasPrecision(4, 2)
                .HasColumnName("tax_rate");

            entity.HasOne(d => d.IdNavigation).WithOne(p => p.SettingCrm)
                .HasForeignKey<SettingCrm>(d => d.Id)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("setting_crm_id_fkey");

            entity.HasOne(d => d.Person).WithMany(p => p.SettingCrms)
                .HasForeignKey(d => d.PersonId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("setting_crm_person_id_fkey");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<SettingCrm> entity);
    }
}
