// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Platform.Server.Models;
using System;
using System.Collections.Generic;

#nullable disable

namespace Platform.Server.Models.Configurations
{
    public partial class StockHeaderConfiguration : IEntityTypeConfiguration<StockHeader>
    {
        public void Configure(EntityTypeBuilder<StockHeader> entity)
        {
            entity.HasKey(e => e.Id).HasName("stock_header_pkey");

            entity.ToTable("stock_header");

            entity.Property(e => e.Id)
                .UseIdentityAlwaysColumn()
                .HasColumnName("id");
            entity.Property(e => e.Creation)
                .HasDefaultValueSql("now()")
                .HasColumnName("creation");
            entity.Property(e => e.Description)
                .HasMaxLength(1280)
                .HasColumnName("description");
            entity.Property(e => e.Kind).HasColumnName("kind");
            entity.Property(e => e.LocationFromId).HasColumnName("location_from_id");
            entity.Property(e => e.LocationToId).HasColumnName("location_to_id");
            entity.Property(e => e.OrderIds).HasColumnName("order_ids");
            entity.Property(e => e.OrganizationId).HasColumnName("organization_id");
            entity.Property(e => e.PersonId).HasColumnName("person_id");
            entity.Property(e => e.ReceiptTime).HasColumnName("receipt_time");
            entity.Property(e => e.Title)
                .HasMaxLength(128)
                .HasColumnName("title");
            entity.Property(e => e.TotalLines).HasColumnName("total_lines");
            entity.Property(e => e.TotalQty)
                .HasPrecision(15, 2)
                .HasColumnName("total_qty");
            entity.Property(e => e.TrackingNumber)
                .HasMaxLength(20)
                .HasColumnName("tracking_number");
            entity.Property(e => e.UserId).HasColumnName("user_id");

            entity.HasOne(d => d.LocationFrom).WithMany(p => p.StockHeaderLocationFroms)
                .HasForeignKey(d => d.LocationFromId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("stock_header_location_from_id_fkey");

            entity.HasOne(d => d.LocationTo).WithMany(p => p.StockHeaderLocationTos)
                .HasForeignKey(d => d.LocationToId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("stock_header_location_to_id_fkey");

            entity.HasOne(d => d.Organization).WithMany(p => p.StockHeaders)
                .HasForeignKey(d => d.OrganizationId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("stock_header_organization_id_fkey");

            entity.HasOne(d => d.Person).WithMany(p => p.StockHeaderPeople)
                .HasForeignKey(d => d.PersonId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("stock_header_person_id_fkey");

            entity.HasOne(d => d.User).WithMany(p => p.StockHeaderUsers)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("stock_header_user_id_fkey");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<StockHeader> entity);
    }
}
