//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkerCMS.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WorkerCMS.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Customer.
        /// </summary>
        internal static string CreateCustomer {
            get {
                return ResourceManager.GetString("CreateCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Address.
        /// </summary>
        internal static string CreatePersonAddress {
            get {
                return ResourceManager.GetString("CreatePersonAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Person Category.
        /// </summary>
        internal static string CreatePersonCategory {
            get {
                return ResourceManager.GetString("CreatePersonCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Person Info.
        /// </summary>
        internal static string CreatePersonInfo {
            get {
                return ResourceManager.GetString("CreatePersonInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Location.
        /// </summary>
        internal static string CreatePersonLocation {
            get {
                return ResourceManager.GetString("CreatePersonLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Person Product.
        /// </summary>
        internal static string CreatePersonProduct {
            get {
                return ResourceManager.GetString("CreatePersonProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Profile.
        /// </summary>
        internal static string CreatePersonProfile {
            get {
                return ResourceManager.GetString("CreatePersonProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Profile Link.
        /// </summary>
        internal static string CreatePersonProfileLink {
            get {
                return ResourceManager.GetString("CreatePersonProfileLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Supplier.
        /// </summary>
        internal static string CreateSupplier {
            get {
                return ResourceManager.GetString("CreateSupplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Person Info.
        /// </summary>
        internal static string DeletePersonInfo {
            get {
                return ResourceManager.GetString("DeletePersonInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Person Product.
        /// </summary>
        internal static string DeletePersonProduct {
            get {
                return ResourceManager.GetString("DeletePersonProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Profile Attachment.
        /// </summary>
        internal static string DeletePersonProfileAttachment {
            get {
                return ResourceManager.GetString("DeletePersonProfileAttachment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Profile Link.
        /// </summary>
        internal static string DeletePersonProfileLink {
            get {
                return ResourceManager.GetString("DeletePersonProfileLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merge Person Category.
        /// </summary>
        internal static string MergePersonCategory {
            get {
                return ResourceManager.GetString("MergePersonCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read Person.
        /// </summary>
        internal static string ReadPerson {
            get {
                return ResourceManager.GetString("ReadPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read Profile.
        /// </summary>
        internal static string ReadPersonProfile {
            get {
                return ResourceManager.GetString("ReadPersonProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort Person Category.
        /// </summary>
        internal static string SortPersonCategory {
            get {
                return ResourceManager.GetString("SortPersonCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Customer.
        /// </summary>
        internal static string UpdateCustomer {
            get {
                return ResourceManager.GetString("UpdateCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Person.
        /// </summary>
        internal static string UpdatePerson {
            get {
                return ResourceManager.GetString("UpdatePerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Person Category.
        /// </summary>
        internal static string UpdatePersonCategory {
            get {
                return ResourceManager.GetString("UpdatePersonCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Person Info.
        /// </summary>
        internal static string UpdatePersonInfo {
            get {
                return ResourceManager.GetString("UpdatePersonInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Person Product.
        /// </summary>
        internal static string UpdatePersonProduct {
            get {
                return ResourceManager.GetString("UpdatePersonProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Profile.
        /// </summary>
        internal static string UpdatePersonProfile {
            get {
                return ResourceManager.GetString("UpdatePersonProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Profile Link.
        /// </summary>
        internal static string UpdatePersonProfileLink {
            get {
                return ResourceManager.GetString("UpdatePersonProfileLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Supplier.
        /// </summary>
        internal static string UpdateSupplier {
            get {
                return ResourceManager.GetString("UpdateSupplier", resourceCulture);
            }
        }
    }
}
