//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkerCMS.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WorkerCMS.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Contact Relation.
        /// </summary>
        internal static string AddContactRelation {
            get {
                return ResourceManager.GetString("AddContactRelation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete Order Line.
        /// </summary>
        internal static string CompleteOrderLine {
            get {
                return ResourceManager.GetString("CompleteOrderLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete PO Line.
        /// </summary>
        internal static string CompletePOLine {
            get {
                return ResourceManager.GetString("CompletePOLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Asset.
        /// </summary>
        internal static string CreateAsset {
            get {
                return ResourceManager.GetString("CreateAsset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Contact.
        /// </summary>
        internal static string CreateContact {
            get {
                return ResourceManager.GetString("CreateContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Customer.
        /// </summary>
        internal static string CreateCustomer {
            get {
                return ResourceManager.GetString("CreateCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Dept.
        /// </summary>
        internal static string CreateDept {
            get {
                return ResourceManager.GetString("CreateDept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Order.
        /// </summary>
        internal static string CreateOrder {
            get {
                return ResourceManager.GetString("CreateOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Order Delivery.
        /// </summary>
        internal static string CreateOrderDelivery {
            get {
                return ResourceManager.GetString("CreateOrderDelivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Order Payment.
        /// </summary>
        internal static string CreateOrderPayment {
            get {
                return ResourceManager.GetString("CreateOrderPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Address.
        /// </summary>
        internal static string CreatePersonAddress {
            get {
                return ResourceManager.GetString("CreatePersonAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Person Category.
        /// </summary>
        internal static string CreatePersonCategory {
            get {
                return ResourceManager.GetString("CreatePersonCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Person Info.
        /// </summary>
        internal static string CreatePersonInfo {
            get {
                return ResourceManager.GetString("CreatePersonInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Location.
        /// </summary>
        internal static string CreatePersonLocation {
            get {
                return ResourceManager.GetString("CreatePersonLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Person Product.
        /// </summary>
        internal static string CreatePersonProduct {
            get {
                return ResourceManager.GetString("CreatePersonProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Profile.
        /// </summary>
        internal static string CreatePersonProfile {
            get {
                return ResourceManager.GetString("CreatePersonProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Profile Link.
        /// </summary>
        internal static string CreatePersonProfileLink {
            get {
                return ResourceManager.GetString("CreatePersonProfileLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create PO.
        /// </summary>
        internal static string CreatePO {
            get {
                return ResourceManager.GetString("CreatePO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create PO Line.
        /// </summary>
        internal static string CreatePOLine {
            get {
                return ResourceManager.GetString("CreatePOLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Product.
        /// </summary>
        internal static string CreateProduct {
            get {
                return ResourceManager.GetString("CreateProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Product Category.
        /// </summary>
        internal static string CreateProductCategory {
            get {
                return ResourceManager.GetString("CreateProductCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Promotion.
        /// </summary>
        internal static string CreatePromotion {
            get {
                return ResourceManager.GetString("CreatePromotion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Supplier.
        /// </summary>
        internal static string CreateSupplier {
            get {
                return ResourceManager.GetString("CreateSupplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Contact Relation.
        /// </summary>
        internal static string DeleteContactRelation {
            get {
                return ResourceManager.GetString("DeleteContactRelation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Order Line.
        /// </summary>
        internal static string DeleteOrderLine {
            get {
                return ResourceManager.GetString("DeleteOrderLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Person Info.
        /// </summary>
        internal static string DeletePersonInfo {
            get {
                return ResourceManager.GetString("DeletePersonInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Person Product.
        /// </summary>
        internal static string DeletePersonProduct {
            get {
                return ResourceManager.GetString("DeletePersonProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Profile Attachment.
        /// </summary>
        internal static string DeletePersonProfileAttachment {
            get {
                return ResourceManager.GetString("DeletePersonProfileAttachment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Profile Link.
        /// </summary>
        internal static string DeletePersonProfileLink {
            get {
                return ResourceManager.GetString("DeletePersonProfileLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete PO Line.
        /// </summary>
        internal static string DeletePOLine {
            get {
                return ResourceManager.GetString("DeletePOLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delect Stock Record.
        /// </summary>
        internal static string DeleteStock {
            get {
                return ResourceManager.GetString("DeleteStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merge Person Category.
        /// </summary>
        internal static string MergePersonCategory {
            get {
                return ResourceManager.GetString("MergePersonCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merge Product Category.
        /// </summary>
        internal static string MergeProductCategory {
            get {
                return ResourceManager.GetString("MergeProductCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Edit BOMs.
        /// </summary>
        internal static string ProductEditBoms {
            get {
                return ResourceManager.GetString("ProductEditBoms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read Asset Sensitive Data.
        /// </summary>
        internal static string ReadAssetSensitiveData {
            get {
                return ResourceManager.GetString("ReadAssetSensitiveData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read Order.
        /// </summary>
        internal static string ReadOrder {
            get {
                return ResourceManager.GetString("ReadOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read Order Line.
        /// </summary>
        internal static string ReadOrderLine {
            get {
                return ResourceManager.GetString("ReadOrderLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read Person.
        /// </summary>
        internal static string ReadPerson {
            get {
                return ResourceManager.GetString("ReadPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read Profile.
        /// </summary>
        internal static string ReadPersonProfile {
            get {
                return ResourceManager.GetString("ReadPersonProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read PO.
        /// </summary>
        internal static string ReadPO {
            get {
                return ResourceManager.GetString("ReadPO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read PO Line.
        /// </summary>
        internal static string ReadPOLine {
            get {
                return ResourceManager.GetString("ReadPOLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read Stock.
        /// </summary>
        internal static string ReadStock {
            get {
                return ResourceManager.GetString("ReadStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recalculate Order.
        /// </summary>
        internal static string RecalculateOrder {
            get {
                return ResourceManager.GetString("RecalculateOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recalculate PO.
        /// </summary>
        internal static string RecalculatePO {
            get {
                return ResourceManager.GetString("RecalculatePO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rollback Order Line.
        /// </summary>
        internal static string RollbackOrderLine {
            get {
                return ResourceManager.GetString("RollbackOrderLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rollback PO Line.
        /// </summary>
        internal static string RollbackPOLine {
            get {
                return ResourceManager.GetString("RollbackPOLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort Order Delivery.
        /// </summary>
        internal static string SortOrderDelivery {
            get {
                return ResourceManager.GetString("SortOrderDelivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort Order Payment.
        /// </summary>
        internal static string SortOrderPayment {
            get {
                return ResourceManager.GetString("SortOrderPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort Person Category.
        /// </summary>
        internal static string SortPersonCategory {
            get {
                return ResourceManager.GetString("SortPersonCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort Product Category.
        /// </summary>
        internal static string SortProductCategory {
            get {
                return ResourceManager.GetString("SortProductCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort Promotion.
        /// </summary>
        internal static string SortPromotion {
            get {
                return ResourceManager.GetString("SortPromotion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Order Line Execution.
        /// </summary>
        internal static string StartOrderLine {
            get {
                return ResourceManager.GetString("StartOrderLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start PO Line Execution.
        /// </summary>
        internal static string StartPOLine {
            get {
                return ResourceManager.GetString("StartPOLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock Assemble.
        /// </summary>
        internal static string StockAssemble {
            get {
                return ResourceManager.GetString("StockAssemble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock Create Line.
        /// </summary>
        internal static string StockCreateLine {
            get {
                return ResourceManager.GetString("StockCreateLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock Init.
        /// </summary>
        internal static string StockInit {
            get {
                return ResourceManager.GetString("StockInit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock Lose.
        /// </summary>
        internal static string StockLose {
            get {
                return ResourceManager.GetString("StockLose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock Order Out.
        /// </summary>
        internal static string StockOrderOut {
            get {
                return ResourceManager.GetString("StockOrderOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock PO In.
        /// </summary>
        internal static string StockPOIn {
            get {
                return ResourceManager.GetString("StockPOIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock Receive.
        /// </summary>
        internal static string StockReceive {
            get {
                return ResourceManager.GetString("StockReceive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock Take.
        /// </summary>
        internal static string StockTake {
            get {
                return ResourceManager.GetString("StockTake", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock Transfer.
        /// </summary>
        internal static string StockTransfer {
            get {
                return ResourceManager.GetString("StockTransfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Asset.
        /// </summary>
        internal static string UpdateAsset {
            get {
                return ResourceManager.GetString("UpdateAsset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Contact Relation.
        /// </summary>
        internal static string UpdateContactRelation {
            get {
                return ResourceManager.GetString("UpdateContactRelation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Culture Label.
        /// </summary>
        internal static string UpdateCulture {
            get {
                return ResourceManager.GetString("UpdateCulture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Customer.
        /// </summary>
        internal static string UpdateCustomer {
            get {
                return ResourceManager.GetString("UpdateCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Dept.
        /// </summary>
        internal static string UpdateDept {
            get {
                return ResourceManager.GetString("UpdateDept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Order.
        /// </summary>
        internal static string UpdateOrder {
            get {
                return ResourceManager.GetString("UpdateOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Order Delivery.
        /// </summary>
        internal static string UpdateOrderDelivery {
            get {
                return ResourceManager.GetString("UpdateOrderDelivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Order Line.
        /// </summary>
        internal static string UpdateOrderLine {
            get {
                return ResourceManager.GetString("UpdateOrderLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Person.
        /// </summary>
        internal static string UpdatePerson {
            get {
                return ResourceManager.GetString("UpdatePerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Person Category.
        /// </summary>
        internal static string UpdatePersonCategory {
            get {
                return ResourceManager.GetString("UpdatePersonCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Person Info.
        /// </summary>
        internal static string UpdatePersonInfo {
            get {
                return ResourceManager.GetString("UpdatePersonInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Person Product.
        /// </summary>
        internal static string UpdatePersonProduct {
            get {
                return ResourceManager.GetString("UpdatePersonProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Profile.
        /// </summary>
        internal static string UpdatePersonProfile {
            get {
                return ResourceManager.GetString("UpdatePersonProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Profile Link.
        /// </summary>
        internal static string UpdatePersonProfileLink {
            get {
                return ResourceManager.GetString("UpdatePersonProfileLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update PO.
        /// </summary>
        internal static string UpdatePO {
            get {
                return ResourceManager.GetString("UpdatePO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update PO Line.
        /// </summary>
        internal static string UpdatePOLine {
            get {
                return ResourceManager.GetString("UpdatePOLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Product.
        /// </summary>
        internal static string UpdateProduct {
            get {
                return ResourceManager.GetString("UpdateProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Product Logo.
        /// </summary>
        internal static string UpdateProductLogo {
            get {
                return ResourceManager.GetString("UpdateProductLogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Product Price.
        /// </summary>
        internal static string UpdateProductPrice {
            get {
                return ResourceManager.GetString("UpdateProductPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Product Unit.
        /// </summary>
        internal static string UpdateProductUnit {
            get {
                return ResourceManager.GetString("UpdateProductUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Promotion.
        /// </summary>
        internal static string UpdatePromotion {
            get {
                return ResourceManager.GetString("UpdatePromotion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update System Settings.
        /// </summary>
        internal static string UpdateSettings {
            get {
                return ResourceManager.GetString("UpdateSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Stock.
        /// </summary>
        internal static string UpdateStock {
            get {
                return ResourceManager.GetString("UpdateStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Stock Line.
        /// </summary>
        internal static string UpdateStockLine {
            get {
                return ResourceManager.GetString("UpdateStockLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Supplier.
        /// </summary>
        internal static string UpdateSupplier {
            get {
                return ResourceManager.GetString("UpdateSupplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update User.
        /// </summary>
        internal static string UpdateUser {
            get {
                return ResourceManager.GetString("UpdateUser", resourceCulture);
            }
        }
    }
}
