// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using NpgsqlTypes;

namespace Platform.Server.Models;

public partial class Address
{
    public int Id { get; set; }

    public short Kind { get; set; }

    public string Name { get; set; } = null!;

    public string? PlaceId { get; set; }

    public string Region { get; set; } = null!;

    public string State { get; set; } = null!;

    public string City { get; set; } = null!;

    public string? District { get; set; }

    public string? Postcode { get; set; }

    public string FormattedAddress { get; set; } = null!;

    public NpgsqlPoint? Location { get; set; }

    public short Provider { get; set; }

    public DateTime Creation { get; set; }

    public short Status { get; set; }

    public virtual ICollection<OrderHeader> OrderHeaders { get; set; } = new List<OrderHeader>();

    public virtual ICollection<Person> People { get; set; } = new List<Person>();

    public virtual ICollection<Person> PeopleNavigation { get; set; } = new List<Person>();
}