// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Platform.Server.Models;

public partial class CoreLog
{
    public long Id { get; set; }

    public int CoreUserId { get; set; }

    public int? CoreOrganizationId { get; set; }

    public string Title { get; set; }

    public string Ip { get; set; }

    public int DeviceId { get; set; }

    public string DeviceName { get; set; }

    public string Culture { get; set; }

    public string Data { get; set; }

    public DateTime Creation { get; set; }

    public virtual CoreOrganization CoreOrganization { get; set; }

    public virtual CoreUser CoreUser { get; set; }

    public virtual CoreUserDevice Device { get; set; }
}