// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Platform.Server.Models;

public partial class CoreApi
{
    public int Id { get; set; }

    public int CoreOrganizationId { get; set; }

    public short Service { get; set; }

    public string Title { get; set; } = null!;

    public string? Endpoint { get; set; }

    public string AppId { get; set; } = null!;

    public string AppSecret { get; set; } = null!;

    public string? Options { get; set; }

    public short? RatePolicy { get; set; }

    public string? AccessToken { get; set; }

    public DateTime? RefreshTime { get; set; }

    public bool Enabled { get; set; }

    public bool Inheritance { get; set; }

    public DateTime Creation { get; set; }

    public virtual CoreOrganization CoreOrganization { get; set; } = null!;
}