// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Platform.Server.Models;

public partial class CoreUser
{
    public int Id { get; set; }

    public string Password { get; set; }

    public string Name { get; set; }

    public string GivenName { get; set; }

    public string FamilyName { get; set; }

    public string ForeignName { get; set; }

    public string Avatar { get; set; }

    public string AssignedId { get; set; }

    public DateTime Creation { get; set; }

    public short Status { get; set; }

    public DateTime? FrozenTime { get; set; }

    public virtual ICollection<CoreUserIdentifier> CoreUserIdentifiers { get; set; } = new List<CoreUserIdentifier>();
}