// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Platform.Server.Models;

public partial class CoreUserDeviceToken
{
    public long Id { get; set; }

    public int DeviceId { get; set; }

    public int? AppId { get; set; }

    public short ResponseType { get; set; }

    public string Culture { get; set; } = null!;

    public string Token { get; set; } = null!;

    public DateTime Expiry { get; set; }

    public string Data { get; set; } = null!;

    public virtual CoreApp? App { get; set; }

    public virtual CoreUserDevice Device { get; set; } = null!;
}