// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Platform.Server.Models;

public partial class CoreOrganizationAppKey
{
    public int Id { get; set; }

    public int CoreOrganizationAppId { get; set; }

    public string AppKey { get; set; }

    public string AppSecret { get; set; }

    public string LocalName { get; set; }

    public string LocalUrl { get; set; }

    public string LocalApi { get; set; }

    public DateTime Creation { get; set; }

    public virtual CoreOrganizationApp CoreOrganizationApp { get; set; }

    public virtual ICollection<CoreUserDeviceToken> CoreUserDeviceTokens { get; set; } = new List<CoreUserDeviceToken>();
}