// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Platform.Server.Models;

public partial class CoreUserIdentifier
{
    public int Id { get; set; }

    public int CoreUserId { get; set; }

    public short Type { get; set; }

    public string Value { get; set; } = null!;

    public short? RefType { get; set; }

    public DateTime Creation { get; set; }

    public virtual CoreUser CoreUser { get; set; } = null!;
}