// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Platform.Server.Models;

public partial class CoreApp
{
    public short Id { get; set; }

    public string Name { get; set; }

    public short IdentityType { get; set; }

    public string WebUrl { get; set; }

    public string HelpUrl { get; set; }

    public string Logo { get; set; }

    public bool IsPublic { get; set; }

    public DateTime Creation { get; set; }

    public bool Enabled { get; set; }

    public bool? RequireLocalUrl { get; set; }

    public virtual ICollection<CoreOrganizationApp> CoreOrganizationApps { get; set; } = new List<CoreOrganizationApp>();
}