// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Platform.Server.Models;

public partial class CoreOrganizationApp
{
    public int Id { get; set; }

    public short CoreAppId { get; set; }

    public int CoreOrganizationId { get; set; }

    public string AppKey { get; set; }

    public string AppSecret { get; set; }

    public string LocalName { get; set; }

    public string LocalUrl { get; set; }

    public DateTime? Expiry { get; set; }

    public short Status { get; set; }

    public DateTime Creation { get; set; }

    public virtual CoreApp CoreApp { get; set; }

    public virtual CoreOrganization CoreOrganization { get; set; }
}