// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Platform.Server.Models;

public partial class CoreDocument
{
    public int Id { get; set; }

    public int? CoreOrganizationId { get; set; }

    public string Kind { get; set; } = null!;

    public string Title { get; set; } = null!;

    public string? Parameters { get; set; }

    public string Template { get; set; } = null!;

    public DateTime RefreshTime { get; set; }

    public List<string>? Cultures { get; set; }

    public virtual CoreOrganization? CoreOrganization { get; set; }
}