// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Platform.Server.Models;

public partial class CoreOrganizationUser
{
    public int Id { get; set; }

    public Guid Uid { get; set; }

    public int CoreOrganizationId { get; set; }

    public int CoreUserId { get; set; }

    public short UserRole { get; set; }

    public short IdentityType { get; set; }

    public string LocalName { get; set; }

    public string LocalAvatar { get; set; }

    public int? Permission { get; set; }

    public string AssignedId { get; set; }

    public string Data { get; set; }

    public DateTime Creation { get; set; }

    public DateTime? Expiry { get; set; }

    public DateTime RefreshTime { get; set; }

    public short Status { get; set; }

    public virtual CoreOrganization CoreOrganization { get; set; }

    public virtual CoreUser CoreUser { get; set; }
}