// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Platform.Server.Models;

public partial class CoreUserDevice
{
    public int Id { get; set; }

    public int CoreUserId { get; set; }

    public short DeviceType { get; set; }

    public string Name { get; set; } = null!;

    public string ClientId { get; set; } = null!;

    public DateTime Creation { get; set; }

    public DateTime LastLogin { get; set; }

    public string? Timezone { get; set; }

    public virtual CoreUser CoreUser { get; set; } = null!;

    public virtual ICollection<CoreUserDeviceToken> CoreUserDeviceTokens { get; set; } = new List<CoreUserDeviceToken>();
}