// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Platform.Server.Models;

public partial class CoreOrganization
{
    public int Id { get; set; }

    public int OwnerId { get; set; }

    public string Name { get; set; }

    public string Brand { get; set; }

    public string Logo { get; set; }

    public string Pin { get; set; }

    public int? ParentId { get; set; }

    public Guid? Uid { get; set; }

    public short Status { get; set; }

    public DateTime Creation { get; set; }

    public string QueryKeyword { get; set; }

    public virtual ICollection<CoreOrganizationApp> CoreOrganizationApps { get; set; } = new List<CoreOrganizationApp>();

    public virtual ICollection<CoreOrganizationChannel> CoreOrganizationChannelOwners { get; set; } = new List<CoreOrganizationChannel>();

    public virtual ICollection<CoreOrganizationChannel> CoreOrganizationChannelPartners { get; set; } = new List<CoreOrganizationChannel>();

    public virtual ICollection<CoreOrganizationUser> CoreOrganizationUsers { get; set; } = new List<CoreOrganizationUser>();

    public virtual ICollection<CoreOrganization> InverseParent { get; set; } = new List<CoreOrganization>();

    public virtual CoreUser Owner { get; set; }

    public virtual CoreOrganization Parent { get; set; }
}