// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Platform.Server.Models;

public partial class CoreOrganizationChannel
{
    public int OwnerId { get; set; }

    public int PartnerId { get; set; }

    public bool Enabled { get; set; }

    public DateTime Creation { get; set; }

    public DateTime RefreshTime { get; set; }

    public virtual CoreOrganization Owner { get; set; }

    public virtual CoreOrganization Partner { get; set; }
}