// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Platform.Server.Models;

public partial class CoreUser
{
    public int Id { get; set; }

    public string Password { get; set; }

    public string Name { get; set; }

    public string GivenName { get; set; }

    public string FamilyName { get; set; }

    public string PreferredName { get; set; }

    public string Avatar { get; set; }

    public DateTime? FrozenTime { get; set; }

    public short? Step { get; set; }

    public string Region { get; set; }

    public string Pin { get; set; }

    public DateTime Creation { get; set; }

    public short Status { get; set; }

    public string LatinGivenName { get; set; }

    public string LatinFamilyName { get; set; }

    public string QueryKeyword { get; set; }

    public List<int> LatestOrganizationIds { get; set; }

    public List<int> LatestAppIds { get; set; }

    public virtual ICollection<CoreAuthCode> CoreAuthCodes { get; set; } = new List<CoreAuthCode>();

    public virtual ICollection<CoreLog> CoreLogs { get; set; } = new List<CoreLog>();

    public virtual ICollection<CoreOrganizationUser> CoreOrganizationUserCoreUsers { get; set; } = new List<CoreOrganizationUser>();

    public virtual ICollection<CoreOrganizationUser> CoreOrganizationUserInviters { get; set; } = new List<CoreOrganizationUser>();

    public virtual ICollection<CoreOrganization> CoreOrganizations { get; set; } = new List<CoreOrganization>();

    public virtual ICollection<CoreUserDevice> CoreUserDevices { get; set; } = new List<CoreUserDevice>();

    public virtual ICollection<CoreUserIdentifier> CoreUserIdentifiers { get; set; } = new List<CoreUserIdentifier>();
}