// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Platform.Server.Models;

public partial class CoreAuthCode
{
    public Guid Id { get; set; }

    public int? CoreUserId { get; set; }

    public short Action { get; set; }

    public string Openid { get; set; } = null!;

    public string Code { get; set; } = null!;

    public DateTime Expiry { get; set; }

    public string Ip { get; set; } = null!;

    public short Times { get; set; }

    public DateTime? Creation { get; set; }

    public string? Data { get; set; }

    public virtual CoreUser? CoreUser { get; set; }
}