// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Platform.Server.Models;

public partial class CoreOrganization
{
    public int Id { get; set; }

    public int OwnerId { get; set; }

    public string Name { get; set; } = null!;

    public string? Brand { get; set; }

    public string? Logo { get; set; }

    public string? Pin { get; set; }

    public int? ParentId { get; set; }

    public Guid? Uid { get; set; }

    public short Status { get; set; }

    public DateTime Creation { get; set; }

    public string? QueryKeyword { get; set; }

    public string Region { get; set; } = null!;

    public virtual ICollection<CoreApi> CoreApis { get; set; } = new List<CoreApi>();

    public virtual ICollection<CoreDocument> CoreDocuments { get; set; } = new List<CoreDocument>();

    public virtual ICollection<CoreOrganizationApp> CoreOrganizationApps { get; set; } = new List<CoreOrganizationApp>();

    public virtual ICollection<FeatureCulture> FeatureCultures { get; set; } = new List<FeatureCulture>();

    public virtual ICollection<CoreOrganization> InverseParent { get; set; } = new List<CoreOrganization>();

    public virtual ICollection<OrderHeader> OrderHeaders { get; set; } = new List<OrderHeader>();

    public virtual CoreUser Owner { get; set; } = null!;

    public virtual CoreOrganization? Parent { get; set; }

    public virtual ICollection<PermissionGroup> PermissionGroups { get; set; } = new List<PermissionGroup>();

    public virtual ICollection<PersonAsset> PersonAssets { get; set; } = new List<PersonAsset>();

    public virtual ICollection<PersonCategory> PersonCategories { get; set; } = new List<PersonCategory>();

    public virtual ICollection<Person> PersonCoreOrganizations { get; set; } = new List<Person>();

    public virtual ICollection<Person> PersonOrgs { get; set; } = new List<Person>();

    public virtual ICollection<ProductCategory> ProductCategories { get; set; } = new List<ProductCategory>();

    public virtual ICollection<ProductUnit> ProductUnits { get; set; } = new List<ProductUnit>();

    public virtual ICollection<Product> Products { get; set; } = new List<Product>();

    public virtual SettingCrm? SettingCrm { get; set; }

    public virtual ICollection<StockHeader> StockHeaders { get; set; } = new List<StockHeader>();
}