// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Platform.Server.Models;

public partial class FeatureCulture
{
    public int Id { get; set; }

    public string Key { get; set; } = null!;

    public string Culture { get; set; } = null!;

    public int? CoreOrganizationId { get; set; }

    public string Title { get; set; } = null!;

    public string? Description { get; set; }

    public string? JsonData { get; set; }

    public virtual CoreOrganization? CoreOrganization { get; set; }
}