// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Platform.Server.Models;

public partial class FeatureKeyword
{
    public int Id { get; set; }

    public string Tag { get; set; } = null!;

    public int CoreOrganizationId { get; set; }

    public int Total { get; set; }

    public short Kind { get; set; }

    public virtual CoreOrganization CoreOrganization { get; set; } = null!;

    public virtual ICollection<Person> People { get; set; } = new List<Person>();

    public virtual ICollection<Product> Products { get; set; } = new List<Product>();
}