// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Platform.Server.Models;

public partial class FinanceAccount
{
    public int Id { get; set; }

    public long PersonId { get; set; }

    public string Bank { get; set; } = null!;

    public string Currency { get; set; } = null!;

    public string AccountNumber { get; set; } = null!;

    public string? Swift { get; set; }

    public string? Description { get; set; }

    public decimal Balance { get; set; }

    public short Status { get; set; }

    public DateTime Creation { get; set; }

    public virtual ICollection<FinanceTransaction> FinanceTransactionAccounts { get; set; } = new List<FinanceTransaction>();

    public virtual ICollection<FinanceTransaction> FinanceTransactionTargetAccounts { get; set; } = new List<FinanceTransaction>();

    public virtual Person Person { get; set; } = null!;
}