// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Platform.Server.Models;

public partial class FinanceTransaction
{
    public long Id { get; set; }

    public short Kind { get; set; }

    public int AccountId { get; set; }

    public string Title { get; set; } = null!;

    public decimal Amount { get; set; }

    public long? OrderId { get; set; }

    public string? ReferenceId { get; set; }

    public long? TargetPersonId { get; set; }

    public int? TargetAccountId { get; set; }

    public long AuthorId { get; set; }

    public DateTime Creation { get; set; }

    public virtual FinanceAccount Account { get; set; } = null!;

    public virtual Person Author { get; set; } = null!;

    public virtual OrderHeader? Order { get; set; }

    public virtual FinanceAccount? TargetAccount { get; set; }

    public virtual Person? TargetPerson { get; set; }
}