// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Platform.Server.Models;

public partial class MyDbContext : DbContext
{
    public MyDbContext(DbContextOptions<MyDbContext> options)
        : base(options)
    {
    }

    public virtual DbSet<CoreUser> CoreUsers { get; set; }

    public virtual DbSet<CoreUserIdentifier> CoreUserIdentifiers { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<CoreUser>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("core_user_pkey");

            entity.ToTable("core_user");

            entity.Property(e => e.Id)
                .UseIdentityAlwaysColumn()
                .HasIdentityOptions(1001L, null, null, null, null, null)
                .HasColumnName("id");
            entity.Property(e => e.AssignedId)
                .HasMaxLength(20)
                .HasColumnName("assigned_id");
            entity.Property(e => e.Avatar)
                .HasMaxLength(256)
                .HasColumnName("avatar");
            entity.Property(e => e.Creation)
                .HasDefaultValueSql("now()")
                .HasColumnName("creation");
            entity.Property(e => e.FamilyName)
                .HasMaxLength(50)
                .HasColumnName("family_name");
            entity.Property(e => e.ForeignName)
                .HasMaxLength(128)
                .HasColumnName("foreign_name");
            entity.Property(e => e.FrozenTime)
                .HasColumnType("timestamp without time zone")
                .HasColumnName("frozen_time");
            entity.Property(e => e.GivenName)
                .HasMaxLength(50)
                .HasColumnName("given_name");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(128)
                .HasColumnName("name");
            entity.Property(e => e.Password)
                .HasMaxLength(128)
                .HasColumnName("password");
            entity.Property(e => e.Status)
                .HasDefaultValue((short)0)
                .HasColumnName("status");
        });

        modelBuilder.Entity<CoreUserIdentifier>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("core_user_identifier_pkey");

            entity.ToTable("core_user_identifier");

            entity.Property(e => e.Id)
                .UseIdentityAlwaysColumn()
                .HasColumnName("id");
            entity.Property(e => e.CoreUserId).HasColumnName("core_user_id");
            entity.Property(e => e.Creation)
                .HasDefaultValueSql("now()")
                .HasColumnName("creation");
            entity.Property(e => e.RefType).HasColumnName("ref_type");
            entity.Property(e => e.Type).HasColumnName("type");
            entity.Property(e => e.Value)
                .IsRequired()
                .HasMaxLength(256)
                .HasColumnName("value");

            entity.HasOne(d => d.CoreUser).WithMany(p => p.CoreUserIdentifiers)
                .HasForeignKey(d => d.CoreUserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("core_user_identifier_core_user_id_fkey");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}