// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Platform.Server.Models.Configurations;
using System;
using System.Collections.Generic;
#nullable enable

namespace Platform.Server.Models;

public partial class MyDbContext : DbContext
{
    public MyDbContext(DbContextOptions<MyDbContext> options)
        : base(options)
    {
    }

    public virtual DbSet<CoreApi> CoreApis { get; set; }

    public virtual DbSet<CoreApp> CoreApps { get; set; }

    public virtual DbSet<CoreAuthCode> CoreAuthCodes { get; set; }

    public virtual DbSet<CoreOrganization> CoreOrganizations { get; set; }

    public virtual DbSet<CoreOrganizationApp> CoreOrganizationApps { get; set; }

    public virtual DbSet<CoreUser> CoreUsers { get; set; }

    public virtual DbSet<CoreUserDevice> CoreUserDevices { get; set; }

    public virtual DbSet<CoreUserDeviceToken> CoreUserDeviceTokens { get; set; }

    public virtual DbSet<CoreUserIdentifier> CoreUserIdentifiers { get; set; }

    public virtual DbSet<FeatureCulture> FeatureCultures { get; set; }

    public virtual DbSet<OrderDelivery> OrderDeliveries { get; set; }

    public virtual DbSet<OrderHeader> OrderHeaders { get; set; }

    public virtual DbSet<OrderLine> OrderLines { get; set; }

    public virtual DbSet<OrderPayment> OrderPayments { get; set; }

    public virtual DbSet<PermissionGroup> PermissionGroups { get; set; }

    public virtual DbSet<PermissionItem> PermissionItems { get; set; }

    public virtual DbSet<Person> People { get; set; }

    public virtual DbSet<PersonAddress> PersonAddresses { get; set; }

    public virtual DbSet<PersonAsset> PersonAssets { get; set; }

    public virtual DbSet<PersonCategory> PersonCategories { get; set; }

    public virtual DbSet<PersonInfo> PersonInfos { get; set; }

    public virtual DbSet<PersonPermissionItem> PersonPermissionItems { get; set; }

    public virtual DbSet<PersonProduct> PersonProducts { get; set; }

    public virtual DbSet<PersonProfile> PersonProfiles { get; set; }

    public virtual DbSet<PersonProfileAttachment> PersonProfileAttachments { get; set; }

    public virtual DbSet<PersonProfileLink> PersonProfileLinks { get; set; }

    public virtual DbSet<PersonRelation> PersonRelations { get; set; }

    public virtual DbSet<Product> Products { get; set; }

    public virtual DbSet<ProductCategory> ProductCategories { get; set; }

    public virtual DbSet<ProductPrice> ProductPrices { get; set; }

    public virtual DbSet<ProductUnit> ProductUnits { get; set; }

    public virtual DbSet<Promotion> Promotions { get; set; }

    public virtual DbSet<SettingCrm> SettingCrms { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.ApplyConfiguration(new Configurations.CoreApiConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.CoreAppConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.CoreAuthCodeConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.CoreOrganizationConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.CoreOrganizationAppConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.CoreUserConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.CoreUserDeviceConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.CoreUserDeviceTokenConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.CoreUserIdentifierConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.FeatureCultureConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.OrderDeliveryConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.OrderHeaderConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.OrderLineConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.OrderPaymentConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.PermissionGroupConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.PermissionItemConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.PersonConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.PersonAddressConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.PersonAssetConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.PersonCategoryConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.PersonInfoConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.PersonPermissionItemConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.PersonProductConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.PersonProfileConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.PersonProfileAttachmentConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.PersonProfileLinkConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.PersonRelationConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.ProductConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.ProductCategoryConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.ProductPriceConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.ProductUnitConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.PromotionConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.SettingCrmConfiguration());

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}
