// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Platform.Server.Models;

public partial class OrderHeader
{
    public long Id { get; set; }

    public int CoreOrganizationId { get; set; }

    public int CoreUserId { get; set; }

    public string? Source { get; set; }

    public string? SourceId { get; set; }

    public string? AssignedId { get; set; }

    public long SellerId { get; set; }

    public long BuyerId { get; set; }

    public string Title { get; set; } = null!;

    public string? Description { get; set; }

    public DateTime? StartDate { get; set; }

    public DateTime? EndDate { get; set; }

    public string Currency { get; set; } = null!;

    public decimal Amount { get; set; }

    public decimal PaidAmount { get; set; }

    public decimal Discount { get; set; }

    public decimal LineDiscount { get; set; }

    public short Lines { get; set; }

    public decimal Items { get; set; }

    public string? Promotions { get; set; }

    public string Culture { get; set; } = null!;

    public short? PaymentId { get; set; }

    public string? PaymentInstruction { get; set; }

    public short? DeliveryId { get; set; }

    public int? AddressId { get; set; }

    public long? ContactId { get; set; }

    public string? DeliveryInstruction { get; set; }

    public DateTime Creation { get; set; }

    public short Status { get; set; }

    public string? Data { get; set; }

    public virtual Address? Address { get; set; }

    public virtual Person Buyer { get; set; } = null!;

    public virtual Person? Contact { get; set; }

    public virtual CoreOrganization CoreOrganization { get; set; } = null!;

    public virtual CoreUser CoreUser { get; set; } = null!;

    public virtual ICollection<OrderLine> OrderLines { get; set; } = new List<OrderLine>();

    public virtual ICollection<PersonProfile> PersonProfiles { get; set; } = new List<PersonProfile>();

    public virtual Person Seller { get; set; } = null!;
}