// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Platform.Server.Models;

public partial class OrderLine
{
    public long Id { get; set; }

    public long OrderId { get; set; }

    public int ProductId { get; set; }

    public string Title { get; set; } = null!;

    public string? Description { get; set; }

    public decimal OriginalPrice { get; set; }

    public decimal CostPrice { get; set; }

    public decimal Price { get; set; }

    public decimal Qty { get; set; }

    public int AssetQty { get; set; }

    public decimal Amount { get; set; }

    public decimal Discount { get; set; }

    public string? Promotions { get; set; }

    public DateTime? StartTime { get; set; }

    public DateTime? EndTime { get; set; }

    public string? Data { get; set; }

    public int? AssetId { get; set; }

    public DateTime Creation { get; set; }

    public short Status { get; set; }

    public long? UserId { get; set; }

    public long? SupplierId { get; set; }

    public decimal? QtyDelivered { get; set; }

    public long? BomId { get; set; }

    public virtual PersonAsset? Asset { get; set; }

    public virtual OrderLine? Bom { get; set; }

    public virtual ICollection<OrderLine> InverseBom { get; set; } = new List<OrderLine>();

    public virtual OrderHeader Order { get; set; } = null!;

    public virtual Product Product { get; set; } = null!;

    public virtual Person? Supplier { get; set; }

    public virtual Person? User { get; set; }
}