// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Platform.Server.Models;

public partial class OrderPayment
{
    public int Id { get; set; }

    public short Kind { get; set; }

    public string Title { get; set; } = null!;

    public int CoreOrganizationId { get; set; }

    public bool IsValid { get; set; }

    public short OrderIndex { get; set; }

    public virtual ICollection<OrderHeader> OrderHeaders { get; set; } = new List<OrderHeader>();
}