// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Platform.Server.Models;

public partial class PermissionGroup
{
    public int Id { get; set; }

    public string Name { get; set; } = null!;

    public short Roles { get; set; }

    public List<short> Items { get; set; } = null!;

    public int? CoreOrganizationId { get; set; }

    public virtual CoreOrganization? CoreOrganization { get; set; }
}