// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Platform.Server.Models;

public partial class PermissionItem
{
    public short Id { get; set; }

    public short Module { get; set; }

    public string Name { get; set; } = null!;

    public virtual ICollection<PersonPermissionItem> PersonPermissionItems { get; set; } = new List<PersonPermissionItem>();
}