// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Platform.Server.Models;

public partial class PersonInfo
{
    public int Id { get; set; }

    public long PersonId { get; set; }

    public short Kind { get; set; }

    public string Identifier { get; set; } = null!;

    public string? Description { get; set; }

    public DateTime Creation { get; set; }

    public int CoreUserId { get; set; }

    public bool? Subscribed { get; set; }

    public bool? IsDefault { get; set; }

    public virtual CoreUser CoreUser { get; set; } = null!;

    public virtual Person Person { get; set; } = null!;
}