// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Platform.Server.Models;

public partial class PersonProfileLink
{
    public long Id { get; set; }

    public long ProfileId { get; set; }

    public short Kind { get; set; }

    public long? TargetProfileId { get; set; }

    public string? Content { get; set; }

    public DateTime Creation { get; set; }

    public long UserId { get; set; }

    public virtual PersonProfile Profile { get; set; } = null!;

    public virtual PersonProfile? TargetProfile { get; set; }

    public virtual Person User { get; set; } = null!;
}