// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Platform.Server.Models;

public partial class PersonRelation
{
    public long PersonId { get; set; }

    public long ContactId { get; set; }

    public short RelationType { get; set; }

    public string? Data { get; set; }

    public string? Description { get; set; }

    public DateTime Creation { get; set; }

    public virtual Person Contact { get; set; } = null!;

    public virtual Person Person { get; set; } = null!;
}