// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using NpgsqlTypes;

namespace Platform.Server.Models;

public partial class PersonAddress
{
    public int Id { get; set; }

    public long PersonId { get; set; }

    public short Kind { get; set; }

    public string Name { get; set; } = null!;

    public string Region { get; set; } = null!;

    public string State { get; set; } = null!;

    public string City { get; set; } = null!;

    public string? District { get; set; }

    public string? Route { get; set; }

    public string? Street { get; set; }

    public string? PostalCode { get; set; }

    public string FormattedAddress { get; set; } = null!;

    public NpgsqlPoint? Location { get; set; }

    public short Provider { get; set; }

    public string? PlaceId { get; set; }

    public DateTime Creation { get; set; }

    public int? ParentId { get; set; }

    public virtual ICollection<PersonAddress> InverseParent { get; set; } = new List<PersonAddress>();

    public virtual ICollection<OrderHeader> OrderHeaders { get; set; } = new List<OrderHeader>();

    public virtual PersonAddress? Parent { get; set; }

    public virtual Person Person { get; set; } = null!;

    public virtual ICollection<PersonProfile> PersonProfiles { get; set; } = new List<PersonProfile>();
}