// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Platform.Server.Models;

public partial class PersonPermissionItem
{
    public long PersonId { get; set; }

    public short PermissionItemId { get; set; }

    public virtual PermissionItem PermissionItem { get; set; } = null!;

    public virtual Person Person { get; set; } = null!;
}