// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Platform.Server.Models;

public partial class PersonAsset
{
    public int Id { get; set; }

    public long PersonId { get; set; }

    public int ProductId { get; set; }

    public long? SupplierId { get; set; }

    public string Sn { get; set; } = null!;

    public string? Description { get; set; }

    public DateTime Expiry { get; set; }

    public short? Times { get; set; }

    public decimal? Amount { get; set; }

    public string? SensitiveData { get; set; }

    public int CoreUserId { get; set; }

    public short Status { get; set; }

    public DateTime Creation { get; set; }

    public string? HealthCheckUrl { get; set; }

    public DateTime? HealthCheckSchedule { get; set; }

    public string? Data { get; set; }

    public int OrgId { get; set; }

    public virtual CoreUser CoreUser { get; set; } = null!;

    public virtual ICollection<OrderLine> OrderLines { get; set; } = new List<OrderLine>();

    public virtual CoreOrganization Org { get; set; } = null!;

    public virtual Person Person { get; set; } = null!;

    public virtual Product Product { get; set; } = null!;

    public virtual Person? Supplier { get; set; }
}