// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Platform.Server.Models;

public partial class PersonProfile
{
    public long Id { get; set; }

    public long PersonId { get; set; }

    public List<long>? Persons { get; set; }

    public long? OrderId { get; set; }

    public short Kind { get; set; }

    public string Title { get; set; } = null!;

    public string Comment { get; set; } = null!;

    public string? Location { get; set; }

    public int? LocationId { get; set; }

    public DateTime HappenDate { get; set; }

    public DateTime? HappenDateEnd { get; set; }

    public int CoreUserId { get; set; }

    public short UserRole { get; set; }

    public DateTime Creation { get; set; }

    public short Status { get; set; }

    public string? Data { get; set; }

    public string? IndexKey { get; set; }

    public virtual CoreUser CoreUser { get; set; } = null!;

    public virtual OrderHeader? Order { get; set; }

    public virtual Person Person { get; set; } = null!;

    public virtual ICollection<PersonProfileAttachment> PersonProfileAttachments { get; set; } = new List<PersonProfileAttachment>();
}