// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Platform.Server.Models;

public partial class PersonProfileAttachment
{
    public long Id { get; set; }

    public long ProfileId { get; set; }

    public string FileName { get; set; } = null!;

    public long FileSize { get; set; }

    public string ContentType { get; set; } = null!;

    public int CoreUserId { get; set; }

    public DateTime Creation { get; set; }

    public virtual CoreUser CoreUser { get; set; } = null!;

    public virtual PersonProfile Profile { get; set; } = null!;
}