// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Platform.Server.Models;

public partial class Person
{
    public long Id { get; set; }

    public Guid Uid { get; set; }

    public int OrganizationId { get; set; }

    public int? CoreOrganizationId { get; set; }

    public int? CoreUserId { get; set; }

    public short? UserRole { get; set; }

    public short? IdentityType { get; set; }

    public bool IsLegalPerson { get; set; }

    public string Name { get; set; } = null!;

    public string? GivenName { get; set; }

    public string? FamilyName { get; set; }

    public string? LatinGivenName { get; set; }

    public string? LatinFamilyName { get; set; }

    public string? PreferredName { get; set; }

    public short? Title { get; set; }

    public string? JobTitle { get; set; }

    public string? Description { get; set; }

    public string? Avatar { get; set; }

    public DateTime? Birthday { get; set; }

    public string? AssignedId { get; set; }

    public List<string>? Regions { get; set; }

    public int? AddressId { get; set; }

    public List<string>? Currencies { get; set; }

    public List<string>? Cultures { get; set; }

    public string? Ethnicity { get; set; }

    public char? Gender { get; set; }

    public short? Height { get; set; }

    public decimal? Weight { get; set; }

    public short? MaritalStatus { get; set; }

    public short? Education { get; set; }

    public short? Degree { get; set; }

    public string? Data { get; set; }

    public DateTime Creation { get; set; }

    public DateTime? Expiry { get; set; }

    public DateTime RefreshTime { get; set; }

    public short Status { get; set; }

    public string? QueryKeyword { get; set; }

    public int? InviterId { get; set; }

    public long? ReportTo { get; set; }

    public string? PoliticalStatus { get; set; }

    public List<int>? CategoryIds { get; set; }

    public long? OwnerId { get; set; }

    public short? OwnerRelation { get; set; }

    public virtual Address? Address { get; set; }

    public virtual CoreOrganization? CoreOrganization { get; set; }

    public virtual CoreUser? CoreUser { get; set; }

    public virtual ICollection<Person> InverseOwner { get; set; } = new List<Person>();

    public virtual ICollection<Person> InverseReportToNavigation { get; set; } = new List<Person>();

    public virtual CoreUser? Inviter { get; set; }

    public virtual ICollection<OrderHeader> OrderHeaderBuyers { get; set; } = new List<OrderHeader>();

    public virtual ICollection<OrderHeader> OrderHeaderContacts { get; set; } = new List<OrderHeader>();

    public virtual ICollection<OrderHeader> OrderHeaderSellers { get; set; } = new List<OrderHeader>();

    public virtual CoreOrganization Organization { get; set; } = null!;

    public virtual Person? Owner { get; set; }

    public virtual ICollection<PersonAsset> PersonAssetPeople { get; set; } = new List<PersonAsset>();

    public virtual ICollection<PersonAsset> PersonAssetSuppliers { get; set; } = new List<PersonAsset>();

    public virtual ICollection<PersonProduct> PersonProducts { get; set; } = new List<PersonProduct>();

    public virtual ICollection<PersonProfile> PersonProfiles { get; set; } = new List<PersonProfile>();

    public virtual ICollection<Promotion> Promotions { get; set; } = new List<Promotion>();

    public virtual Person? ReportToNavigation { get; set; }

    public virtual ICollection<Address> Addresses { get; set; } = new List<Address>();

    public virtual ICollection<CoreUser> CoreUsers { get; set; } = new List<CoreUser>();

    public virtual ICollection<FeatureKeyword> FeatureKeywords { get; set; } = new List<FeatureKeyword>();
}