// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Platform.Server.Models;

public partial class PersonProduct
{
    public long PersonId { get; set; }

    public int ProductId { get; set; }

    public string? Name { get; set; }

    public string? Description { get; set; }

    public string? AssignedId { get; set; }

    public string? Currency { get; set; }

    public decimal? RetailPrice { get; set; }

    public DateTime UpdatedTime { get; set; }

    public virtual Person Person { get; set; } = null!;

    public virtual Product Product { get; set; } = null!;
}