// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Platform.Server.Models;

public partial class ProductPrice
{
    public int ProductId { get; set; }

    public string Currency { get; set; } = null!;

    public decimal RetailPrice { get; set; }

    public decimal? PromotionPrice { get; set; }

    public decimal? ChannelPrice { get; set; }

    public decimal? CostPrice { get; set; }

    public DateTime Creation { get; set; }

    public virtual Product Product { get; set; } = null!;
}