// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Platform.Server.Models;

public partial class Product
{
    public int Id { get; set; }

    public int CoreOrganizationId { get; set; }

    public string Name { get; set; } = null!;

    public string? ForeignName { get; set; }

    public List<int> CategoryIds { get; set; } = null!;

    public string? Description { get; set; }

    public string? Logo { get; set; }

    public int UnitId { get; set; }

    public decimal? MinQty { get; set; }

    public decimal? StepQty { get; set; }

    public decimal? CapQty { get; set; }

    public short? AssetUnit { get; set; }

    public int? AssetQty { get; set; }

    public short OrderIndex { get; set; }

    public DateTime Creation { get; set; }

    public short Status { get; set; }

    public short Usage { get; set; }

    public short Scope { get; set; }

    public string? Data { get; set; }

    public string? QueryKeyword { get; set; }

    public short InventoryWay { get; set; }

    public List<int>? Tags { get; set; }

    public virtual CoreOrganization CoreOrganization { get; set; } = null!;

    public virtual ICollection<OrderLine> OrderLines { get; set; } = new List<OrderLine>();

    public virtual ICollection<PersonAsset> PersonAssets { get; set; } = new List<PersonAsset>();

    public virtual ICollection<PersonProduct> PersonProducts { get; set; } = new List<PersonProduct>();

    public virtual ICollection<ProductCulture> ProductCultures { get; set; } = new List<ProductCulture>();

    public virtual ICollection<ProductPrice> ProductPrices { get; set; } = new List<ProductPrice>();

    public virtual ICollection<Promotion> Promotions { get; set; } = new List<Promotion>();

    public virtual ProductUnit Unit { get; set; } = null!;
}