// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Platform.Server.Models;

public partial class ProductUnit
{
    public int Id { get; set; }

    public int? CoreOrganizationId { get; set; }

    public string Name { get; set; } = null!;

    public short OrderIndex { get; set; }

    public virtual CoreOrganization? CoreOrganization { get; set; }

    public virtual ICollection<Product> Products { get; set; } = new List<Product>();
}