// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Platform.Server.Models;

public partial class ProductBom
{
    public int Id { get; set; }

    public int ParentId { get; set; }

    public int ProductId { get; set; }

    public decimal Qty { get; set; }

    public virtual Product Parent { get; set; } = null!;

    public virtual Product Product { get; set; } = null!;
}