// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Platform.Server.Models;

public partial class ProductCategory
{
    public int Id { get; set; }

    public List<string> Names { get; set; } = null!;

    public string? Logo { get; set; }

    public string? Data { get; set; }

    public DateTime Creation { get; set; }

    public int? ParentId { get; set; }

    public short OrderIndex { get; set; }

    public int CoreOrganizationId { get; set; }

    public virtual CoreOrganization CoreOrganization { get; set; } = null!;

    public virtual ICollection<ProductCategory> InverseParent { get; set; } = new List<ProductCategory>();

    public virtual ProductCategory? Parent { get; set; }

    public virtual ICollection<Promotion> Promotions { get; set; } = new List<Promotion>();
}