// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Platform.Server.Models;

public partial class ProductCulture
{
    public int ProductId { get; set; }

    public string Culture { get; set; } = null!;

    public string Name { get; set; } = null!;

    public string? Description { get; set; }

    public string? Data { get; set; }

    public virtual Product Product { get; set; } = null!;
}