// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Platform.Server.Models;

public partial class Promotion
{
    public int Id { get; set; }

    public int CoreOrganizationId { get; set; }

    public string Title { get; set; } = null!;

    public string Currency { get; set; } = null!;

    public int? ProductId { get; set; }

    public int? ProductCategoryId { get; set; }

    public long? PersonId { get; set; }

    public int? PersonCategoryId { get; set; }

    public short Code { get; set; }

    public decimal MinAmount { get; set; }

    public int Discount { get; set; }

    public DateTime ValidStart { get; set; }

    public DateTime ValidEnd { get; set; }

    public int Coupons { get; set; }

    public bool Stackable { get; set; }

    public short OrderIndex { get; set; }

    public DateTime Creation { get; set; }

    public short Status { get; set; }

    public virtual CoreOrganization CoreOrganization { get; set; } = null!;

    public virtual Person? Person { get; set; }

    public virtual PersonCategory? PersonCategory { get; set; }

    public virtual Product? Product { get; set; }

    public virtual ProductCategory? ProductCategory { get; set; }
}