// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Platform.Server.Models;

public partial class SettingCrm
{
    public int Id { get; set; }

    public long PersonId { get; set; }

    public short MainCustomerType { get; set; }

    public List<string> Currencies { get; set; } = null!;

    public List<string> SupplierCurrencies { get; set; } = null!;

    public List<string> Cultures { get; set; } = null!;

    public bool HasInventory { get; set; }

    public virtual CoreOrganization IdNavigation { get; set; } = null!;

    public virtual Person Person { get; set; } = null!;
}