// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Platform.Server.Models;

public partial class StockSite
{
    public long Id { get; set; }

    public int ProductId { get; set; }

    public int? LocationId { get; set; }

    public decimal? Qty { get; set; }

    public DateTime RefreshTime { get; set; }

    public virtual PersonAddress? Location { get; set; }

    public virtual Product Product { get; set; } = null!;
}