// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Platform.Server.Models;

public partial class StockHeader
{
    public long Id { get; set; }

    public int OrganizationId { get; set; }

    public short Kind { get; set; }

    public long PersonId { get; set; }

    public int LocationFromId { get; set; }

    public int LocationToId { get; set; }

    public long UserId { get; set; }

    public string Title { get; set; } = null!;

    public string? Description { get; set; }

    public string? TrackingNumber { get; set; }

    public List<long>? OrderIds { get; set; }

    public DateTime? ReceiptTime { get; set; }

    public DateTime Creation { get; set; }

    public virtual PersonAddress LocationFrom { get; set; } = null!;

    public virtual PersonAddress LocationTo { get; set; } = null!;

    public virtual CoreOrganization Organization { get; set; } = null!;

    public virtual Person Person { get; set; } = null!;

    public virtual ICollection<StockLine> StockLines { get; set; } = new List<StockLine>();

    public virtual Person User { get; set; } = null!;
}