// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Platform.Server.Models;

public partial class StockLine
{
    public long Id { get; set; }

    public long StockId { get; set; }

    public int ProductId { get; set; }

    public int LocationId { get; set; }

    public decimal Qty { get; set; }

    public long? OrderLineId { get; set; }

    public virtual PersonAddress Location { get; set; } = null!;

    public virtual OrderLine? OrderLine { get; set; }

    public virtual Product Product { get; set; } = null!;

    public virtual StockHeader Stock { get; set; } = null!;
}