//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkerCenter.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WorkerCenter.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept Invitation.
        /// </summary>
        internal static string AcceptInvitation {
            get {
                return ResourceManager.GetString("AcceptInvitation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have accepted &lt;b&gt;{0}&lt;/b&gt;&apos;s invitation to join &lt;b&gt;{1}&lt;/b&gt;..
        /// </summary>
        internal static string AcceptInvitationDetail {
            get {
                return ResourceManager.GetString("AcceptInvitationDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [SmartERP] {0} Notice.
        /// </summary>
        internal static string ActionNoticeSubject {
            get {
                return ResourceManager.GetString("ActionNoticeSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add User Identifier.
        /// </summary>
        internal static string AddUserIdentifier {
            get {
                return ResourceManager.GetString("AddUserIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type: &lt;b&gt;{0}&lt;/b&gt;, Value: &lt;b&gt;{1}&lt;/b&gt;.
        /// </summary>
        internal static string AddUserIdentifierDetail {
            get {
                return ResourceManager.GetString("AddUserIdentifierDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        internal static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create API Key.
        /// </summary>
        internal static string CreateApiKey {
            get {
                return ResourceManager.GetString("CreateApiKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Member.
        /// </summary>
        internal static string DeleteMember {
            get {
                return ResourceManager.GetString("DeleteMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;{0}&lt;/b&gt; removed member &lt;b&gt;{2}&lt;/b&gt; from &lt;b&gt;{1}&lt;/b&gt; (invited by: {3}).
        /// </summary>
        internal static string DeleteMemberDetail {
            get {
                return ResourceManager.GetString("DeleteMemberDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete User Identifier.
        /// </summary>
        internal static string DeleteUserIdentifier {
            get {
                return ResourceManager.GetString("DeleteUserIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invitation Accepted.
        /// </summary>
        internal static string InvitationAccepted {
            get {
                return ResourceManager.GetString("InvitationAccepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;{0}&lt;/b&gt; has accepted your invitation to join &lt;b&gt;{1}&lt;/b&gt;..
        /// </summary>
        internal static string InvitationAcceptedDetail {
            get {
                return ResourceManager.GetString("InvitationAcceptedDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave Organization.
        /// </summary>
        internal static string LeaveOrg {
            get {
                return ResourceManager.GetString("LeaveOrg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;{0}&lt;/b&gt; (inviter: {1}) left &lt;b&gt;{2}&lt;/b&gt; on his own initiative.
        /// </summary>
        internal static string LeaveOrgDetail {
            get {
                return ResourceManager.GetString("LeaveOrgDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Failed.
        /// </summary>
        internal static string LoginFailed {
            get {
                return ResourceManager.GetString("LoginFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Frozen.
        /// </summary>
        internal static string LoginFailedFrozenAction {
            get {
                return ResourceManager.GetString("LoginFailedFrozenAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Due to multiple failed login attempts, your account has been frozen for 30 minutes. Please try again after 30 minutes..
        /// </summary>
        internal static string LoginFailedFrozenDetail {
            get {
                return ResourceManager.GetString("LoginFailedFrozenDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Success.
        /// </summary>
        internal static string LoginSuccess {
            get {
                return ResourceManager.GetString("LoginSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Password.
        /// </summary>
        internal static string ResetPassword {
            get {
                return ResourceManager.GetString("ResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Application.
        /// </summary>
        internal static string UpdateApp {
            get {
                return ResourceManager.GetString("UpdateApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Member.
        /// </summary>
        internal static string UpdateMember {
            get {
                return ResourceManager.GetString("UpdateMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Member Avatar.
        /// </summary>
        internal static string UpdateMemberAvatar {
            get {
                return ResourceManager.GetString("UpdateMemberAvatar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Organization.
        /// </summary>
        internal static string UpdateOrg {
            get {
                return ResourceManager.GetString("UpdateOrg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Organization Avatar.
        /// </summary>
        internal static string UpdateOrgAvatar {
            get {
                return ResourceManager.GetString("UpdateOrgAvatar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Avatar.
        /// </summary>
        internal static string UpdateUserAvatar {
            get {
                return ResourceManager.GetString("UpdateUserAvatar", resourceCulture);
            }
        }
    }
}
