//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkerCenter.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WorkerCenter.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept Invitation.
        /// </summary>
        internal static string AcceptInvitation {
            get {
                return ResourceManager.GetString("AcceptInvitation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have accepted &lt;b&gt;{0}&lt;/b&gt;&apos;s invitation to join &lt;b&gt;{1}&lt;/b&gt;..
        /// </summary>
        internal static string AcceptInvitationDetail {
            get {
                return ResourceManager.GetString("AcceptInvitationDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [SmartERP] {0} Notice.
        /// </summary>
        internal static string ActionNoticeSubject {
            get {
                return ResourceManager.GetString("ActionNoticeSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add User Identifier.
        /// </summary>
        internal static string AddUserIdentifier {
            get {
                return ResourceManager.GetString("AddUserIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type: &lt;b&gt;{0}&lt;/b&gt;, Value: &lt;b&gt;{1}&lt;/b&gt;.
        /// </summary>
        internal static string AddUserIdentifierDetail {
            get {
                return ResourceManager.GetString("AddUserIdentifierDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batch Adjustment of Reporting.
        /// </summary>
        internal static string AdjustReportTo {
            get {
                return ResourceManager.GetString("AdjustReportTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;{1}&lt;/b&gt; people who previously reported to &lt;b&gt;{0}&lt;/b&gt; have been batch adjusted to report to &lt;b&gt;{2}&lt;/b&gt;..
        /// </summary>
        internal static string AdjustReportToDetail {
            get {
                return ResourceManager.GetString("AdjustReportToDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin Clear User Frozen Time.
        /// </summary>
        internal static string AdminClearUserFrozen {
            get {
                return ResourceManager.GetString("AdminClearUserFrozen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin Renew Application.
        /// </summary>
        internal static string AdminRenewApp {
            get {
                return ResourceManager.GetString("AdminRenewApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application &lt;b&gt;{0}&lt;/b&gt; of &lt;b&gt;{3}&lt;/b&gt; has been renewed by the administrator for &lt;b&gt;{1}&lt;/b&gt; months, and no payment is required. The following are the notes: &lt;blockquote&gt;{2}&lt;/blockquote&gt;.
        /// </summary>
        internal static string AdminRenewAppDetail {
            get {
                return ResourceManager.GetString("AdminRenewAppDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin technical support login.
        /// </summary>
        internal static string AdminSupport {
            get {
                return ResourceManager.GetString("AdminSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;{0}&lt;/b&gt; has given you permission to log in as the user for the purpose of providing technical support, and has been approved by {1}. More details: &lt;blockquote&gt;{2}&lt;/blockquote&gt;.
        /// </summary>
        internal static string AdminSupportDetail {
            get {
                return ResourceManager.GetString("AdminSupportDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy Application.
        /// </summary>
        internal static string BuyApp {
            get {
                return ResourceManager.GetString("BuyApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        internal static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login application.
        /// </summary>
        internal static string CheckSession {
            get {
                return ResourceManager.GetString("CheckSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add external API.
        /// </summary>
        internal static string CreateApi {
            get {
                return ResourceManager.GetString("CreateApi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create API Key.
        /// </summary>
        internal static string CreateApiKey {
            get {
                return ResourceManager.GetString("CreateApiKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Business Document.
        /// </summary>
        internal static string CreateDocument {
            get {
                return ResourceManager.GetString("CreateDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Organization.
        /// </summary>
        internal static string CreateOrg {
            get {
                return ResourceManager.GetString("CreateOrg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create or update resource.
        /// </summary>
        internal static string CreateResource {
            get {
                return ResourceManager.GetString("CreateResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Business Document.
        /// </summary>
        internal static string DeleteDocument {
            get {
                return ResourceManager.GetString("DeleteDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Member.
        /// </summary>
        internal static string DeleteMember {
            get {
                return ResourceManager.GetString("DeleteMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;{0}&lt;/b&gt; removed member &lt;b&gt;{2}&lt;/b&gt; from &lt;b&gt;{1}&lt;/b&gt; (invited by: {3}).
        /// </summary>
        internal static string DeleteMemberDetail {
            get {
                return ResourceManager.GetString("DeleteMemberDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete User Identifier.
        /// </summary>
        internal static string DeleteUserIdentifier {
            get {
                return ResourceManager.GetString("DeleteUserIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invitation Accepted.
        /// </summary>
        internal static string InvitationAccepted {
            get {
                return ResourceManager.GetString("InvitationAccepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;{0}&lt;/b&gt; has accepted your invitation to join &lt;b&gt;{1}&lt;/b&gt;..
        /// </summary>
        internal static string InvitationAcceptedDetail {
            get {
                return ResourceManager.GetString("InvitationAcceptedDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave Organization.
        /// </summary>
        internal static string LeaveOrg {
            get {
                return ResourceManager.GetString("LeaveOrg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;{0}&lt;/b&gt; (inviter: {1}) left &lt;b&gt;{2}&lt;/b&gt; on his own initiative.
        /// </summary>
        internal static string LeaveOrgDetail {
            get {
                return ResourceManager.GetString("LeaveOrgDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Failed.
        /// </summary>
        internal static string LoginFailed {
            get {
                return ResourceManager.GetString("LoginFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Frozen.
        /// </summary>
        internal static string LoginFailedFrozenAction {
            get {
                return ResourceManager.GetString("LoginFailedFrozenAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Due to multiple failed login attempts, your account has been frozen for 30 minutes. Please try again after 30 minutes..
        /// </summary>
        internal static string LoginFailedFrozenDetail {
            get {
                return ResourceManager.GetString("LoginFailedFrozenDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Success.
        /// </summary>
        internal static string LoginSuccess {
            get {
                return ResourceManager.GetString("LoginSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Platform administrator operation.
        /// </summary>
        internal static string PlatformAdminOperation {
            get {
                return ResourceManager.GetString("PlatformAdminOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renew Application.
        /// </summary>
        internal static string RenewApp {
            get {
                return ResourceManager.GetString("RenewApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Password.
        /// </summary>
        internal static string ResetPassword {
            get {
                return ResourceManager.GetString("ResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch Organization.
        /// </summary>
        internal static string SwitchOrg {
            get {
                return ResourceManager.GetString("SwitchOrg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update external API.
        /// </summary>
        internal static string UpdateApi {
            get {
                return ResourceManager.GetString("UpdateApi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Application.
        /// </summary>
        internal static string UpdateApp {
            get {
                return ResourceManager.GetString("UpdateApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Business Document.
        /// </summary>
        internal static string UpdateDocument {
            get {
                return ResourceManager.GetString("UpdateDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Member.
        /// </summary>
        internal static string UpdateMember {
            get {
                return ResourceManager.GetString("UpdateMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Member Avatar.
        /// </summary>
        internal static string UpdateMemberAvatar {
            get {
                return ResourceManager.GetString("UpdateMemberAvatar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Organization.
        /// </summary>
        internal static string UpdateOrg {
            get {
                return ResourceManager.GetString("UpdateOrg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Organization Avatar.
        /// </summary>
        internal static string UpdateOrgAvatar {
            get {
                return ResourceManager.GetString("UpdateOrgAvatar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Avatar.
        /// </summary>
        internal static string UpdateUserAvatar {
            get {
                return ResourceManager.GetString("UpdateUserAvatar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update User Self Data.
        /// </summary>
        internal static string UpdateUserSelf {
            get {
                return ResourceManager.GetString("UpdateUserSelf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User email password callback code.
        /// </summary>
        internal static string UserCallbackEmailCode {
            get {
                return ResourceManager.GetString("UserCallbackEmailCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User SMS password callback code.
        /// </summary>
        internal static string UserCallbackSMSCode {
            get {
                return ResourceManager.GetString("UserCallbackSMSCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User email registration code.
        /// </summary>
        internal static string UserRegistrationEmailCode {
            get {
                return ResourceManager.GetString("UserRegistrationEmailCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User SMS registration code.
        /// </summary>
        internal static string UserRegistrationSMSCode {
            get {
                return ResourceManager.GetString("UserRegistrationSMSCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User email address verification code.
        /// </summary>
        internal static string UserVerificationEmailCode {
            get {
                return ResourceManager.GetString("UserVerificationEmailCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User mobile phone number verification code.
        /// </summary>
        internal static string UserVerificationSMSCode {
            get {
                return ResourceManager.GetString("UserVerificationSMSCode", resourceCulture);
            }
        }
    }
}
