name: Deploy Service

on:
  workflow_call:
    inputs:
      region:
        required: true
        type: string
        description: "Target deployment region"
      version:
        required: true
        type: string
        description: "Image version to be deployed"

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      SSH_HOST: ${{ secrets[format('{0}_SSH_HOST', inputs.region)] }}
      SSH_PORT: ${{ secrets[format('{0}_SSH_PORT', inputs.region)] }}
      SSH_USER: ${{ secrets[format('{0}_SSH_USER', inputs.region)] }}
      SSH_KEY: ${{ secrets[format('{0}_SSH_KEY', inputs.region)] }}
      RELEASE: "deploy/releases/${{ inputs.version }}"
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: SSH Deploy
        shell: bash
        run: |
          set -euo pipefail

          echo "Preparing remote release: ~/${RELEASE}"

          ssh \
            -p "${SSH_PORT}" \
            "${SSH_USER}@${SSH_HOST}" \
            "rm -rf \"~/${RELEASE}\" && mkdir -p \"~/${RELEASE}\""

          echo "Copying ./helm to ~/${RELEASE}..."

          tar czf - -C . helm | \
            ssh \
              -p "${SSH_PORT}" \
              "${SSH_USER}@${SSH_HOST}" \
              "tar xzf - -C \"~/${RELEASE}\""

          echo "Helm files copied successfully."

          ssh \
            -p "${SSH_PORT}" \
            "${SSH_USER}@${SSH_HOST}" \
            "ls -la \"~/${RELEASE}/helm\""

      - name: Helm deploy
        shell: bash
        run: |
          ssh \
            -p "${SSH_PORT}" \
            "${SSH_USER}@${SSH_HOST}" \
            "microk8s helm3 upgrade smarterp ~/${RELEASE}/helm \
              --install \
              --post-renderer ./scripts/post-render.sh \
              --atomic \
              --wait \
              --timeout 10m"

  release:
    needs: deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Create or Update GitHub Release
        env:
          GH_TOKEN: ${{ github.token }}
        shell: bash
        run: |
          VERSION="${{ inputs.version }}"
          TAG="release-${VERSION}"

          echo "=========================================="
          echo "🔍 Checking release: $TAG"
          echo "=========================================="

          if gh release view "$TAG" >/dev/null 2>&1; then

            gh release edit "$TAG" \
              --title "Release $VERSION" \
              --generate-notes
              
            echo "✅ Release $TAG updated successfully!"

          else

            echo "Creating release $TAG"

            gh release create "$TAG" \
              --title "Release $VERSION" \
              --generate-notes
              
            echo "✅ Release $TAG created successfully!"

          fi
