name: Build

on:
  workflow_call:
    inputs:
      version:
        description: Build version
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Show build info
        run: |
          echo "Build version: ${{ inputs.version }}"

      - name: Checkout
        uses: actions/checkout@v5
