name: Deploy

on:
  workflow_dispatch:
    inputs:
      version:
        description: Deploy version, like 1.2.3
        required: true
        type: string
      region:
        description: "Target region"
        required: true
        type: choice
        options:
          - CN
          - AU
        default: CN

jobs:
  show-info:
    runs-on: ubuntu-latest

    steps:
      - name: Validate version
        env:
          GH_TOKEN: ${{ github.token }}
        shell: bash
        run: |
          VERSION=${{ inputs.version }}

          TAG="release-${VERSION}"

          echo "Checking release: $TAG"

          if gh release view "$TAG" >/dev/null 2>&1; then

            echo "Release $TAG exists, proceed to deploy"

          else

            echo "Release $TAG does not exist"

            exit 1

          fi

      - name: Show deployment info
        run: |
          echo "Deploy version: ${{ inputs.version }}"
          echo "Region: ${{ inputs.region }}"

  deploy-cn:
    if: inputs.region == 'CN'

    uses: ./.github/workflows/deploy-CN.yml

    with:
      version: ${{ inputs.version }}

  deploy-au:
    if: inputs.region == 'AU'

    uses: ./.github/workflows/deploy-AU.yml

    with:
      version: ${{ inputs.version }}
