name: Deploy AU

on:
  workflow_call:
    inputs:
      version:
        description: Deploy version
        required: true
        type: string

jobs:
  show-info:
    runs-on: ubuntu-latest

    steps:
      - name: Show deployment info
        run: |
          echo "Deploy version: ${{ inputs.version }}"
